### DISCUSSION TITLE
how to define vmsize in epiphany config yml 2.0.4 version.

### DISCUSSION THREAD

**Discussion by MurugaAzure** [epiphany-platform/epiphany#3323] [Q&A]
Hello @przemyslavic,

 I did configuration for vm size ("Standard_DS2_v3") in epiphany 2.0.4 version but default vm size is ("Standard_DS1_v2") creation.

  Could you please help me? How to define vmsize for cluster machine and worker node vm?

configuration: 

````
kind: infrastructure/virtual-machine
title: Virtual Machine Infra
provider: azure
name: default-monitoring
specification:
  size: #{monitoring-size}#
  storage_os_disk:
    disk_size_gb: 64
version: 2.0.4

````

**Comment by przemyslavic** [comment]
@MurugaAzure 
You simply change the size of a particular vm like this:
```yaml
---
kind: infrastructure/virtual-machine
name: repository-machine
provider: azure
specification:
  size: Standard_D2s_v3
```
![image](https://user-images.githubusercontent.com/43173646/218132133-7683bbfc-1e47-49ca-aad1-e3410bde020e.png)

You can find a list of all machines here: https://github.com/epiphany-platform/epiphany/blob/v2.0/schema/azure/defaults/epiphany-cluster.yml#L27

From what I see you change the size of `default-monitoring` vm which is probably never used as by default for monitoring component the proper name is `monitoring-machine`. If you want to use custom names for vms you should specify them in doc `kind: epiphany-cluster` and then provide their definition in doc `kind: infrastructure/virtual-machine`.
