### ISSUE TITLE
[AWS] - ASG duplicate issue with  infrastructure/virtual-machine definitions re-use

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#1084]
Multiple uses of the same infrastructure/virtual-machine definitions for components results in duplicate asg’s which causes Terraform to fail:

```yaml
kind: epiphany-cluster
title: Epiphany cluster Config
provider: aws
name: default
specification:
  name: test
  prefix: epi
  admin_user:
    name: ubuntu
    key_path: 
  cloud:
    use_public_ips: true
    credentials:
      key: 
      secret: 
  components:
    kafka:
      count: 1
      machine: cdl-machine
    kubernetes_master:
      count: 1
      machine: cdl-machine
    kubernetes_node:
      count: 0
    load_balancer:
      count: 0
    logging:
      count: 0
    monitoring:
      count: 0
    postgresql:
      count: 0
    rabbitmq:
      count: 0
version: 0.6.0
---
kind: infrastructure/virtual-machine
title: "Virtual Machine Infra"
provider: aws
name: cdl-machine
specification:
  size: t3.medium
  security:
    rules:
     - name: ssh
       description: Allow SSH
       priority: 101
       direction: Inbound
       access: Allow
       protocol: Tcp
       source_port_range: "*"
       destination_port_range: "22"
       source_address_prefix: "0.0.0.0/0"
       destination_address_prefix: "0.0.0.0/0"
     - name: ignite_traffic
       description: Allow traffic to Apache Ignite cluster
       priority: 302
       direction: Inbound
       access: Allow
       protocol: ALL
       source_port_range: "*"
       destination_from_port: 0
       destination_to_port: 48300
       destination_port_range: "0"
       source_address_prefix: "10.1.0.0/20"
       destination_address_prefix: "10.1.0.0/20"
     - name: out
       description: Allow out
       priority: 101
       direction: Egress
       access: Allow
       protocol: "all"
       source_port_range: "*"
       destination_port_range: "0"
       source_address_prefix: "0.0.0.0/0"
       destination_address_prefix: "0.0.0.0/0"
```
