### ISSUE TITLE
Re-run single machine installation may fail

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#1182]
Repro steps:
1) Run single-machine installation with added `haproxy` role mapping

```
15:37:42 INFO cli.engine.ansible.AnsibleCommand - TASK [haproxy : Copy haproxy config] *********************************************************************************************
**************************************************
15:37:42 INFO cli.engine.ansible.AnsibleCommand - fatal: [wilku-XXX-single-machine-vm-0]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'kubernetes_node'"}
```

2) Change config to (`single_machine` instead of `kubernetes_node` in `server_groups` of `backend`: section):
```
---
kind: configuration/haproxy
title: HAProxy
name: default
specification:
  version: '1.8'
  service_port: 30001
  logs_max_days: 60
  self_signed_certificate_name: self-signed-fullchain.pem
  self_signed_private_key_name: self-signed-privkey.pem
  self_signed_concatenated_cert_name: self-signed-test.tld.pem
  haproxy_log_path: /var/log/haproxy.log
  stats:
    enable: true
    bind_address: 127.0.0.1:9000
    uri: /haproxy?stats
    user: operations
    password: your-haproxy-stats-pwd
  frontend:
  - name: https_front
    port: 443
    https: yes
    backend:
    - http_back1
  backend:
  - name: http_back1
    server_groups:
    - single_machine
    port: 30104
version: 0.6.0
provider: azure
---

```
3) Re-run epicli:
`15:47:19 ERROR epicli - ControlPlane downscale is not supported yet. Please revert your kubernetes_master count to previous value or increase it to scale up kubernetes.`

Marcin Wilk's comments:

> /usr/local/lib/python3.7/site-packages/cli/engine/ApplyEngine.py assert_no_master_downscale.
> This check by default seems okay, however in SINGLE MACHINE scenario is an issue. I'm gonna try replace kubernetes_master to single_machine there. I did create 1 VM cluster with only single_machine role. Then it get broken during Ansible part because of HAProxy configuration. It is new cluster and fresh yaml created (modified) today, based on default `-p azure --full`.
