### ISSUE TITLE
PostgreSQL replication not working on Ubuntu when not using repmgr

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#1260]
PostgreSQL config:
```
---
kind: configuration/postgresql
name: default
provider: aws
specification:
  config_file:
    parameter_groups:
    - name: REPLICATION
      subgroups:
        - name: Sending Server(s)
          parameters:
            - name: max_wal_senders
              value: 10 # default value
              comment: maximum number of simultaneously running WAL sender processes
              when: replication # default value
            - name: wal_keep_segments
              value: 34 # default value
              comment: number of WAL files held for standby servers
              when: replication
  extensions:
    pgaudit:
      enabled: yes
    pgbouncer:
      enabled: yes
    replication:
      enabled: yes
      use_repmgr: no
      shared_preload_libraries: []
title: PostgreSQL

```
Ansible reports no errors, but nodes are not clustered.

**Comment by przemyslavic** [comment]
The correct configuration should be as follows (as described in the '[how to](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/DATABASES.md)' guide):
```
    replication:
      enabled: yes
      use_repmgr: no
      shared_preload_libraries: []
```
