### ISSUE TITLE
PostgreSQL replication with repmgr: hot_standby not set in config file

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#1273]
**Describe the bug**
Hot standby mode is not enabled on a PostgreSQL replica on RedHat environemnts despite running a task that should enable it.

**To Reproduce**
1. Deploy a cluster with 2 PostgreSQL vms

**Expected behavior**
Hot standby mode is enabled on a PostgreSQL replica node.

**Actual behavior**
The log file looks good but there is no effect in the configuration file.
```
2020-05-14T07:26:58.9085515Z 07:26:58 INFO cli.engine.ansible.AnsibleCommand - TASK [postgresql : Turn on hot_standby] ****************************************
2020-05-14T07:26:58.9316048Z 07:26:58 INFO cli.engine.ansible.AnsibleCommand - skipping: [ec2-xx-xx-xx-xx.eu-west-3.compute.amazonaws.com]
2020-05-14T07:26:59.4780903Z 07:26:59 INFO cli.engine.ansible.AnsibleCommand - changed: [ec2-yy-yy-yy-yy.eu-west-3.compute.amazonaws.com]
```

```
[root@ec2-yy-yy-yy-yy ~]# cat /var/lib/pgsql/10/data/postgresql.conf | grep hot
#old_snapshot_threshold = -1            # 1min-60d; -1 disables; 0 is immediate
#hot_standby = on                       # "off" disallows queries during recovery
#hot_standby_feedback = off             # send info from standby to prevent
```

**Config files**
Configuration that should be included in the yaml file:
```yaml
...
    postgresql:
      count: 2
      machine: postgresql-machine-rhel
...
---
kind: infrastructure/virtual-machine
name: postgresql-machine-rhel
provider: aws
based_on: postgresql-machine
specification:
  os_full_name: RHEL-7.8_HVM_GA-20200225-x86_64-1-Hourly2-GP2
---
kind: configuration/postgresql
name: default
provider: aws
specification:
  extensions:
    pgaudit:
      enabled: yes
    pgbouncer:
      enabled: yes
    replication:
      enabled: yes
      use_repmgr: yes
title: Postgresql
```

**OS (please complete the following information):**
 - OS: [RHEL]

**Cloud Environment (please complete the following information):**
 - Cloud Provider [all]
