### ISSUE TITLE
Helm: Single Helm chart installation within other roles with custom values support

### ISSUE THREAD

**Issue by ar3ndt** [epiphany-platform/epiphany#1289]

**Comment by ar3ndt** [comment]
Helm charts are exposed within apache repository. Single Helm chart installation is a separate task in Helm role responsible of installing already existing chart from repo.
Single Helm chart task has to be included in each particular role that needs to install chart.
It is possible to overwrite chart values within the specification config. 

Example usage:
```

---
- name: Set Helm chart values from custom configuration
  set_fact:
    _helm_chart_values: "{{ specification.helm_chart_values }}"
  when: specification.helm_chart_values is defined
- name: Set Helm chart name from custom configuration
  set_fact:
    _helm_chart_name: "{{ specification.helm_chart_name }}"
  when: specification.helm_chart_name is defined
- name: Set Helm chart disable flag from custom configuration
  set_fact:
    _disable_helm_chart: "{{ specification.disable_helm_chart }}"
  when: specification.disable_helm_chart is defined
- name: Mychart
  include_role:
    name: helm
    tasks_from: install-chart
  vars:
    disable_helm_chart: "{{ _disable_helm_chart }}"
    helm_chart_name: "{{ _helm_chart_name }}"
    helm_chart_values:  "{{ _helm_chart_values }}"
```
Example config:

```
kind: configuration/helm-mychart
title: "Helm mychart"
name: default
specification:
  helm_chart_name: mychart
  disable_helm_chart: false
  helm_chart_values:
    service:
      port: 8080
    nameOverride: mychart_custom_name
```
