### ISSUE TITLE
Implement proper merging of lists of dictionaries for epicli yaml docs

### ISSUE THREAD

**Issue by sk4zuzu** [epiphany-platform/epiphany#1294]
Epiphany's default yaml merger does not take into account that any document can be a mix of dictionaries and lists. There are two issues with that:
1. When dictionary is defined inside a list, then it's not properly converted to internal dictionary implementation `ObjDict`.
2. Merging user config with default config (in case of lists of dictionaries present inside) does not set default values at all, it means that full config structure must be always provided by the user.

**Comment by sk4zuzu** [comment]
> 2. Merging user config with default config (in case of lists of dictionaries present inside) does not set default values at all, it means that full config structure must be always provided by the user.

This could be implemented for structures like:
```yaml
  available_roles:
    - name: repository
      enabled: yes
    - name: firewall
      enabled: yes
    - name: image-registry
      enabled: yes
    - name: kubernetes-master
      enabled: yes
    - name: kubernetes-node
      enabled: yes
```
which is basically a dictionary implemented with lists, where the key is the value of then `name:`.

There is a existing counter-example though:
```yaml
  supported_os:
    - name: RedHat
      comparison_operator: "=="
      version: 7.6
    - name: RedHat
      comparison_operator: "=="
      version: 7.7
    - name: RedHat
      comparison_operator: "=="
      version: 7.8
    - name: RedHat
      comparison_operator: "=="
      version: 7.9
    - name: CentOS
      comparison_operator: "=="
      version: 7.6
    - name: CentOS
```
both of these structures cannot be megred in the same way.

IMO, in the end, it seems to be better to leave the default behavior of replacing lists (like for example docker-compose does) and convert existing dictionary-like structures (implemented with lists) to proper dictionaries.

**Comment by sk4zuzu** [comment]
This issue needs to be reconsidered. We cannot fix this problem by introducing another way to merge yaml docs. The correct approach is to fix yaml document schema, but this is not a backward-compatible operation.

**Comment by mkyc** [comment]
@sk4zuzu can you please confirm that this is still valid task?

**Comment by seriva** [comment]
Yes its a problem, no I dont think we should spend time on fixing this in legacy Epiphany. @toszo @sk4zuzu @mkyc what do you think? Close it?

**Comment by sk4zuzu** [comment]
If the general consensus would be that we focus on new things, then considering this is not so easy to implement it in a generic way and we have been living without it since he beginning of time (:D), we can close it IMO.

**Comment by seriva** [comment]
Yeah, redefining the schema is better done for the new module based approach. This is still something that people can work arround by defining the entire defaults when making changes.

**Comment by seriva** [comment]
Re-opening as one of the cases is no longer in effect making this issue maybe solvable:

```yaml
supported_os:
    - name: RedHat
      comparison_operator: "=="
      version: 7.6
    - name: RedHat
      comparison_operator: "=="
      version: 7.7
    - name: RedHat
      comparison_operator: "=="
      version: 7.8
    - name: RedHat
      comparison_operator: "=="
      version: 7.9
    - name: CentOS
      comparison_operator: "=="
      version: 7.6
    - name: CentOS
```

**Comment by przemyslavic** [comment]
:heavy_check_mark: I tested some different configurations for PostgreSQL, applications, feature-mapping. It looks like finally we have proper merging of dictionaries and lists.
What I especially like is enabling the applications in this simple way :)

```
---
kind: configuration/applications
title: "Kubernetes Applications Config"
provider: aws
name: default
specification:
  applications:
  - name: rabbitmq
    enabled: true
  - name: ignite-stateless
    enabled: true
  - name: auth-service
    enabled: true
  - name: pgpool
    enabled: false
  - name: pgbouncer
    enabled: false
  - name: istio
    enabled: false
```
User does not have to provide full configuration when making some changes within dictionaries and lists at different levels. The default values are used when user does not provide configuration.

**Comment by przemyslavic** [comment]
:heavy_check_mark: Tested again after refactoring done in connected PR.
More unit tests have also been added.

**Comment by przemyslavic** [comment]
Tested again after refactoring done in connected PR.
More unit tests have also been added.

@to-bar found a case where it isn't always a good idea to merge lists.
For example, providing such a configuration:
```
---
kind: configuration/kafka
title: "Kafka"
name: default
provider: aws
specification:
  kafka_var:
    security:
      authorization:
        users:
          - name: xxx
            topic: yyy
```
results in merging with the defaults
```
---
kind: configuration/kafka
title: Kafka
name: default
specification:
  kafka_var:
    security:
      authorization:
        users:
        - name: test_user
          topic: test_topic
        - name: xxx
          topic: yyy
```
causing 2 users to be added which the user may not be aware of.
This can be a security risk. It can be even worse, for example, in the case of a list with directories to be deleted.
As discussed with @to-bar, a good solution would be to introduce the `_inherit_mode` parameter, thanks to which we would set the merge mode to `overwrite` or `merge`, with `overwrite` by default as it was so far.

EDIT:
It fails when trying to upgrade from epicli <1.0.
The error is as follows:
`ERROR epicli - "name" field with value "RedHat" occurs multiple times in list "supported_os" in default definition.`
This is because of multiple values in `shared-config`: https://github.com/epiphany-platform/epiphany/blob/v0.9/core/src/epicli/data/common/defaults/configuration/shared-config.yml.
This preflight check was refactored in v1.0 #2150. We have to take into account that there may be old installations/cluster with just such a shared configuration that will not pass the validation check during the upgrade.

**Comment by przemyslavic** [comment]
:heavy_check_mark: Fixed. 
Parameter `_merge` has been introduced for named lists. If not provided or set to `false` (by default) the user must provide all list items because its configuration will override the defaults. If set to `true`, the values provided by the user will be merged with the defaults, which is very helpful, e.g. when enabling applications. Instead of providing all the configuration for all apps, you just need the code below to deploy them:
```
---
kind: configuration/applications
title: "Kubernetes Applications Config"
provider: aws
name: default
specification:
  applications:
  - _merge: true
  - name: rabbitmq
    enabled: true
  - name: ignite-stateless
    enabled: true
  - name: auth-service
    enabled: true
  - name: pgpool
    enabled: true
  - name: pgbouncer
    enabled: true
  - name: istio
    enabled: true
```
