### ISSUE TITLE
[FEATURE REQUEST] Allow to check on VMs which epicli version was used to deploy/upgrade components

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#1306]
**Is your feature request related to a problem? Please describe.**
Right now we can recognize the version of epicli by specific k8s version on masters/nodes.

**Describe the solution you'd like**
We want to dump the version number of executed epicli on cluster components (VMs) to easily recognize which version is deployed. We can also think about feature to add a history of upgrades if they were any. 

**Describe alternatives you've considered**
None.

**Additional context**
None.

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by mkyc** [comment]
@rafzei do you mean that: 

```
*****EPICLI VERSION******
0.6.0
```

?
Those lines are currently at the top of generated dump.

**Comment by rafzei** [comment]
@mkyc I mean 'target' VMs not a epicli one. I've edit the issue description - I hope it has more sense right now.

**Comment by to-bar** [comment]
Today I was asked about such functionality so it's really needed.

**Comment by atsikham** [comment]
Optional, but with that feature we can skip following step in `data/common/ansible/playbooks/roles/image_registry/tasks/load-image.yml` if there is an upgrade to the same version:

```yaml
- name: Load legacy version images to registry when upgrading
   include_tasks: load-image.yml
   vars:
     docker_image: "{{ item }}"
   loop: "{{ specification.images_to_load.legacy }}"
   when: is_upgrade_run
```

**Comment by mkyc** [comment]
Such information is presented in MOTD now (see #2628)

**Comment by atsikham** [comment]
> Such information is presented in MOTD now (see #2628)

Right, but only during login and there is no any upgrade history that @rafzei mentioned in description.

**Comment by rafzei** [comment]
Yup, I think adding some ~/.version or ~/.epicli file containing that information would be a good solution here.

.epicli:
```
# type - date - version
Apply - 11:30:00 27-09-2021 - 1.3.0dev
```

**Comment by mkyc** [comment]
Or `/etc/epiphany/version`. But yes, log would be much better.

**Comment by przemyslavic** [comment]
:heavy_check_mark: When executing `apply` and `upgrade` commands, the appropriate entries with execution status are added to the `/var/lib/epiphany/history.yml` file:
```
[ec2-user@ec2-1-1-1-1 ~]$ cat /var/lib/epiphany/history.yml
deployments:
- date: '2021-11-15 11:49:24'
  mode: apply
  status: completed
  version: 1.3.0dev
- date: '2021-11-15 11:29:22'
  mode: upgrade
  status: completed
  version: 1.3.0dev
- date: '2021-11-15 11:28:36'
  mode: upgrade
  status: failed
  version: 1.3.0dev
- date: '2021-11-15 11:11:42'
  mode: apply
  status: completed
  version: 1.3.0dev
- date: '2021-11-15 10:29:18'
  mode: apply
  status: completed
  version: 1.3.0dev
```

Now #2715 should be done as related task.
