### ISSUE TITLE
Automate updating of security rules when different network and subnet layouts are applied in the main ```epiphany-cluster``` document

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#1317]
Currently the netwerk and submet layout is defined in the main ```epiphany-cluster``` document under the '''component''' tag:

```yaml
...
components:
    kubernetes_master:
      count: 1
      machine: kubernetes-master-machine
      configuration: default
      subnets:
      - availability_zone: eu-west-2a
        address_pool: 10.1.1.0/24
      - availability_zone: eu-west-2b
        address_pool: 10.1.2.0/24
    kubernetes_node:
      count: 2
      machine: kubernetes-node-machine
      configuration: default
      subnets:
      - availability_zone: eu-west-2a
        address_pool: 10.1.1.0/24
      - availability_zone: eu-west-2b
        address_pool: 10.1.2.0/24
...
```

However for Azure`s ```Network security groups``` and AWS`s ```Security Groups``` the rules are defined under the different ```infrastructure/virtual-machine``` tied to the different defined components:

AWS:
```yaml
kind: infrastructure/virtual-machine
title: Virtual Machine Infra
provider: aws
name: default
...
  security:
    rules:
    - name: ssh
      description: Allow SSH
      priority: 101
      direction: Inbound
      access: Allow
      protocol: Tcp
      source_port_range: '*'
      destination_port_range: '22'
      source_address_prefix: 0.0.0.0/0
      destination_address_prefix: 0.0.0.0/0
..
```

Azure:
```yaml
kind: infrastructure/virtual-machine
title: Virtual Machine Infra
provider: azure
name: default
...
  security:
    rules:
    - name: ssh
      description: Allow SSH
      priority: 100
      direction: Inbound
      access: Allow
      protocol: Tcp
      source_port_range: '*'
      destination_port_range: '22'
      source_address_prefix: '*'
      destination_address_prefix: '*'
..
```

Currently if a team changes the component network layout they also need to go in and change all ```infrastructure/virtual-machine``` definitions to match that layout. For the default network security rules changes in network layout should be automaticly reflected.
