### ISSUE TITLE
Cannot deploy a non-k8s cluster with load_balancer vm

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#1350]
A non-k8s cluster cannot be deployed with the load balancer vm because the default values for the haproxy configuration point to the kubernetes_node group.
```
2020-06-10T10:06:52.9946497Z 10:06:52 INFO cli.engine.ansible.AnsibleCommand - TASK [haproxy : Copy haproxy config] *******************************************
2020-06-10T10:06:53.2138234Z 10:06:53 INFO cli.engine.ansible.AnsibleCommand - fatal: [ec2-35-180-21-217.eu-west-3.compute.amazonaws.com]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'kubernetes_node'"}

```

```
  backend: # example backend config below
    - name: http_back1
      server_groups:
      - kubernetes_node
      # servers: # Definition for server to that hosts the application.
      # - name: "node1"
      #   address: "epiphany-vm1.domain.com"
      port: 30104
```
