### ISSUE TITLE
Epicli does not correctly generate vars for Postgres

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#1370]
Tested on role Postgres.
When copy some of variables into cluster-config.yml to tune values, only these values are imported to component section in manifest file. Other values from defaults are not imported.
This problem occured when any parameter from config file was added to main.yaml

Probably AnsibleVarsGenerator needs to be modified

Steps to reproduce:
1.  Add values from configuration/postgres specification.config_file to config.yml (not whole component section), example:
```
kind: configuration/postgresql
name: default
provider: any
specification:
  config_file:
    parameter_groups:
    - name: WRITE AHEAD LOG
      subgroups:
      - name: Settings
        parameters:
        - name: wal_level
          value: replica
          when: replication
title: PostgreSQL
version: 0.6.0
```
2. Run epicli apply and check manifest file after vars generation. Only WRITE AHEAD LOG section is added to manifest file. Rest parameters under config_file section are not imported (should be imported from defaults).
Epicli does not merge keys under config_file

**Comment by sk4zuzu** [comment]
Please check this comment https://github.com/epiphany-platform/epiphany/issues/1294#issuecomment-633873541.

**Comment by rafzei** [comment]
As sk4zuzu mentioned in his issue, it's probably because we are not handling nested lists in dictionaries properly. I see we agreed that schema changes shouldn't be implemented in 'standard epicli', instead we should work on this in the modules approach.
On the other hand, this may be a small change in our python script for this particular issue (only Postgres role).
@seriva what do you think?

**Comment by seriva** [comment]
Ill have a peak.

**Comment by przemyslavic** [comment]
:heavy_check_mark: Seems to be fixed in PR #2465.
I checked different parameters for PostgreSQL, changed some configuration at different levels, and it looks like the default values are used in case the user does not provide full configuration. And then the merged configuration is present in the manifest.yml file.

**Comment by przemyslavic** [comment]
Tested again after refactoring done in connected PR #2465.
The manifest file looks good after merging the user-set values with the defaults.

Further comments / discussion in related task #1294.

**Comment by przemyslavic** [comment]
Until now, in the case of lists, we had to provide the full configuration for a given component, not just the items we wanted to change, because the user configuration override the default values. Now an additional parameter `_merge` has been introduced that allows you to set whether you want to overwrite the default values or merge them. In this case, for example, to change only the name of the log directory, it is enough to provide only specific section from the configuration and for each named list add the "_merge" parameter set to `true`:
```
---
kind: configuration/postgresql
title: PostgreSQL
provider: aws
name: default
specification:
  config_file:
    parameter_groups:
      - _merge: true
      - name: ERROR REPORTING AND LOGGING
        subgroups:
          - _merge: true
          - name: Where to Log
            parameters:
              - _merge: true
              - name: log_directory
                value: "'/var/log/postgresqltest'"
                comment: to have standard location for Filebeat and logrotate
```
