### ISSUE TITLE
[BUG] Epicli does not create Postgresql SET_BY_AUTOMATION values correctly

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#1372]
**Describe the bug**
Epicli init does not add values at_by_automation into code. Terraform part works correctly, but it does not import for ansible part. this is not issue with epicli, default postgresql configurations need to be re-arranged
**To Reproduce**
1. execute `epicli init --full`
2. edit config file (enable postgresql)
3. execute `epicli apply - f file`. Deployment from file generated with option --full will fail

**Expected behavior**
Deployment from file generated with option --full will fail with exception:
Error running: \"ansible-playbook -i /shared/build/de13onprem/inventory --vault-password-file /root/.epicli/vault.cfg /shared/build/de13onprem/ansible/postgresql.yml 

```
{"asctime": "13:46:29", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": "fatal: [usatl-s-plblah2]: FAILED! => {"}
{"asctime": "13:46:29", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": "    \"changed\": false,"}
{"asctime": "13:46:29", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": "    \"msg\": \"AnsibleUndefinedVariable: 'dict object' has no attribute 'value'\""}
{"asctime": "13:46:29", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": "}"}
{"asctime": "13:46:29", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": "fatal: [usatl-s-plblah3]: FAILED! => {"}
{"asctime": "13:46:29", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": "    \"changed\": false,"}
{"asctime": "13:46:29", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": "    \"msg\": \"AnsibleUndefinedVariable: 'dict object' has no attribute 'value'\""}
{"asctime": "13:46:29", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": "}"}
{"asctime": "13:46:29", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": ""}
{"asctime": "13:46:29", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": "PLAY RECAP 
```

**Config files**
```
specification:
  config_file:
    parameter_groups:
    - name: CONNECTIONS AND AUTHENTICATION
      subgroups:
      - name: Connection Settings
        parameters:
        - name: listen_addresses
          value: "'*'"
          comment: listen on all addresses
      - name: Security and Authentication
        parameters:
        - name: ssl
          value: off
          comment: to have the default value also on Ubuntu
    - name: RESOURCE USAGE (except WAL)
      subgroups:
      - name: Kernel Resource Usage
        parameters:
        - name: shared_preload_libraries
          comment: set by automation
```

**OS (please complete the following information):**
 - OS: Ubuntu 18.04 (any)

**Cloud Environment (please complete the following information):**
 - On Prem (but it's ansible part)

**Additional context**
Don't use SET_BY_AUTOMATION in default configs since these values are stored in epicli code and are not visible in manifest file.
