### ISSUE TITLE
[BUG] custom_image_registry_address setting is not implemented

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1409]
**Describe the bug**
When value `custom_image_registry_address` is used in configuration installation fails. 

**To Reproduce**
1. create separate repository and images registry (I do it by creating machine using roles: image-registry, repository and firewall)
2. create configuration with customisation parameters
  ```
  custom_repository_url: 'http://192.168.88.99/epirepo'
  custom_image_registry_address: 'https://192.168.88.99:5000'
  ```
3. execute `epicli apply -f config-file.yml --no-infra`

**Expected behavior**
setup cluster

**Error:**
```wrap
"fatal: [kmaster]: FAILED! => {\"changed\": true, \"cmd\": \"kubeadm init  --config /etc/kubeadm/kubeadm-config.yml\\n\", \"delta\": \"0:00:01.137324\", \"end\": \"2020-07-01 11:51:22.041120\", \"msg\": \"non-zero return code\", \"rc\": 1, \"start\": \"2020-07-01 11:51:20.903796\", \"stderr\": \"W0701 11:51:20.958148   18663 validation.go:28] Cannot validate kube-proxy config - no validator is available\\nW0701 11:51:20.958220   18663 validation.go:28] Cannot validate kubelet config - no validator is available\\n\\t[WARNING IsDockerSystemdCheck]: detected \\\"cgroupfs\\\" as the Docker cgroup driver. The recommended driver is \\\"systemd\\\". Please follow the guide at https://kubernetes.io/docs/setup/cri/\\n\\t[WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'\\nerror execution phase preflight: [preflight] Some fatal errors occurred:\\n\\t[ERROR ImagePull]: failed to pull image https://192.168.88.99:5000/k8s.gcr.io/kube-apiserver:v1.17.7: output: invalid reference format\\n, error: exit status 1\\n\\t[ERROR ImagePull]: failed to pull image https://192.168.88.99:5000/k8s.gcr.io/kube-controller-manager:v1.17.7: output: invalid reference format\\n, error: exit status 1\\n\\t[ERROR ImagePull]: failed to pull image https://192.168.88.99:5000/k8s.gcr.io/kube-scheduler:v1.17.7: output: invalid reference format\\n, error: exit status 1\\n\\t[ERROR ImagePull]: failed to pull image https://192.168.88.99:5000/k8s.gcr.io/kube-proxy:v1.17.7: output: invalid reference format\\n, error: exit status 1\\n\\t[ERROR ImagePull]: failed to pull image https://192.168.88.99:5000/k8s.gcr.io/pause:3.1: output: invalid reference format\\n, error: exit status 1\\n\\t[ERROR ImagePull]: failed to pull image https://192.168.88.99:5000/k8s.gcr.io/etcd:3.4.3-0: output: invalid reference format\\n, error: exit status 1\\n\\t[ERROR ImagePull]: failed to pull image https://192.168.88.99:5000/k8s.gcr.io/coredns:1.6.5: output: invalid reference format\\n, error: exit status 1\\n[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`\\nTo see the stack trace of this error execute with --v=5 or higher\", \"stderr_lines\": [\"W0701 11:51:20.958148   18663 validation.go:28] Cannot validate kube-proxy config - no validator is available\", \"W0701 11:51:20.958220   18663 validation.go:28] Cannot validate kubelet config - no validator is available\", \"\\t[WARNING IsDockerSystemdCheck]: detected \\\"cgroupfs\\\" as the Docker cgroup driver. The recommended driver is \\\"systemd\\\". Please follow the guide at https://kubernetes.io/docs/setup/cri/\", \"\\t[WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'\", \"error execution phase preflight: [preflight] Some fatal errors occurred:\", \"\\t[ERROR ImagePull]: failed to pull image https://192.168.88.99:5000/k8s.gcr.io/kube-apiserver:v1.17.7: output: invalid reference format\", \", error: exit status 1\", \"\\t[ERROR ImagePull]: failed to pull image https://192.168.88.99:5000/k8s.gcr.io/kube-controller-manager:v1.17.7: output: invalid reference format\", \", error: exit status 1\", \"\\t[ERROR ImagePull]: failed to pull image https://192.168.88.99:5000/k8s.gcr.io/kube-scheduler:v1.17.7: output: invalid reference format\", \", error: exit status 1\", \"\\t[ERROR ImagePull]: failed to pull image https://192.168.88.99:5000/k8s.gcr.io/kube-proxy:v1.17.7: output: invalid reference format\", \", error: exit status 1\", \"\\t[ERROR ImagePull]: failed to pull image https://192.168.88.99:5000/k8s.gcr.io/pause:3.1: output: invalid reference format\", \", error: exit status 1\", \"\\t[ERROR ImagePull]: failed to pull image https://192.168.88.99:5000/k8s.gcr.io/etcd:3.4.3-0: output: invalid reference format\", \", error: exit status 1\", \"\\t[ERROR ImagePull]: failed to pull image https://192.168.88.99:5000/k8s.gcr.io/coredns:1.6.5: output: invalid reference format\", \", error: exit status 1\", \"[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`\", \"To see the stack trace of this error execute with --v=5 or higher\"], \"stdout\": \"[init] Using Kubernetes version: v1.17.7\\n[preflight] Running pre-flight checks\\n[preflight] Pulling images required for setting up a Kubernetes cluster\\n[preflight] This might take a minute or two, depending on the speed of your internet connection\\n[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'\", \"stdout_lines\": [\"[init] Using Kubernetes version: v1.17.7\", \"[preflight] Running pre-flight checks\", \"[preflight] Pulling images required for setting up a Kubernetes cluster\", \"[preflight] This might take a minute or two, depending on the speed of your internet connection\", \"[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'\"]}"}
```

**OS:**
 - OS: centos 7

**Cloud Environment:**
 - any, I do it localy

**Comment by mkyc** [comment]
@seriva can you compare it with your error? Was it the same?

**Comment by seriva** [comment]
I had the same issue. Problem is that when `custom_image_registry_address` is set on master and nodes in `/etc/docker/daemon.json` the `insecure-registries` entry is not set. If you set this manually to permit the registry then it works fine. More info [here](https://docs.docker.com/registry/insecure/).

Second issue is that when deploying the different K8s components the generated k8s deployment yamls are also pointing to the registry which normally would be running on master. This resulting in failure to deploy of the k8s system components. The application deployments might also be effected but I did not test this jet.

For deploying a standalone registry this yaml can be used:

```yaml
kind: epiphany-cluster
title: Epiphany cluster Config
provider: any
name: default
specification:
  name: uburepo
  admin_user:
    name: operations
    key_path: /home/vscode/ssh/id_rsa_epi
  components:
    kubernetes_master:
      count: 0
      machines:
      - default-k8s-master1
    kubernetes_node:
      count: 0
      machines:
      - default-k8s-node1
      - default-k8s-node2
    logging:
      count: 0
      machines:
      - default-logging
    monitoring:
      count: 0
      machines:
      - default-monitoring
    kafka:
      count: 0
      machines:
      - default-kafka1
      - default-kafka2
    postgresql:
      count: 0
      machines:
      - default-postgresql
    load_balancer:
      count: 0
      machines:
      - default-loadbalancer
    rabbitmq:
      count: 0
      machines:
      - default-rabbitmq
    repo_only:
      count: 1
      configuration: default
      machines:
      - repomachine
---
version: 0.7.0
kind: configuration/feature-mapping
title: "Feature mapping to roles"
name: default
provider: any
specification:
  available_roles:
    - name: repository
      enabled: yes
    - name: firewall
      enabled: yes
    - name: image-registry
      enabled: yes
    - name: kubernetes-master
      enabled: yes
    - name: kubernetes-node
      enabled: yes
    - name: helm
      enabled: yes
    - name: logging
      enabled: yes
    - name: opendistro-for-elasticsearch
      enabled: yes
    - name: elasticsearch
      enabled: yes
    - name: elasticsearch-curator
      enabled: yes
    - name: kibana
      enabled: yes
    - name: filebeat
      enabled: yes
    - name: prometheus
      enabled: yes
    - name: grafana
      enabled: yes
    - name: node-exporter
      enabled: yes
    - name: jmx-exporter
      enabled: yes
    - name: zookeeper
      enabled: yes
    - name: kafka
      enabled: yes
    - name: rabbitmq
      enabled: yes
    - name: kafka-exporter
      enabled: yes
    - name: postgresql
      enabled: yes
    - name: haproxy
      enabled: yes
    - name: haproxy-exporter
      enabled: yes
    - name: vault
      enabled: yes
    - name: applications
      enabled: yes
    - name: ignite
      enabled: yes
  roles_mapping:
    kafka:
      - zookeeper
      - jmx-exporter
      - kafka
      - kafka-exporter
      - node-exporter
      - filebeat
      - firewall
    rabbitmq:
      - rabbitmq
      - node-exporter
      - filebeat
      - firewall
    logging:
      - logging
      - kibana
      - node-exporter
      - filebeat
      - firewall
    load_balancer:
      - haproxy
      - haproxy-exporter
      - node-exporter
      - filebeat
      - firewall
    monitoring:
      - prometheus
      - grafana
      - node-exporter
      - filebeat
      - firewall
    postgresql:
      - postgresql
      - node-exporter
      - filebeat
      - firewall
    custom:
      - repository
      - image-registry
      - kubernetes-master
      - node-exporter
      - filebeat
      - rabbitmq
      - postgresql
      - prometheus
      - grafana
      - node-exporter
      - logging
      - firewall
    single_machine:
      - repository
      - image-registry
      - kubernetes-master
      - helm
      - applications
      - rabbitmq
      - postgresql
      - firewall
    kubernetes_master:
      - image-registry
      - kubernetes-master
      - repository
      - helm
      - applications
      - node-exporter
      - filebeat
      - firewall
      - vault
    kubernetes_node:
      - kubernetes-node
      - node-exporter
      - filebeat
      - firewall
    ignite:
      - ignite
      - node-exporter
      - filebeat
      - firewall
    opendistro_for_elasticsearch:
      - opendistro-for-elasticsearch
      - node-exporter
      - filebeat
      - firewall
    repo_only:
      - image-registry
      - repository
      - firewall
---
kind: infrastructure/machine
provider: any
name: repomachine
specification:
  hostname: ubunturepo1
  ip: 192.168.100.126
version: 0.7.0
---
kind: configuration/repository
provider: any
title: "Epiphany requirements repository"
name: default
specification:
  description: "Local repository of binaries required to install Epiphany"
  download_done_flag_expire_minutes: 120
  apache_epirepo_path: "/var/www/html/epirepo"
  teardown:
    disable_http_server: false # whether to stop and disable Apache HTTP Server service
```
