### ISSUE TITLE
[BUG] Missing `manifest.yml` and `terraform.tfstate` during upgrade

### ISSUE THREAD

**Issue by pyrkamarcin** [epiphany-platform/epiphany#1410]
**Describe the bug**
1. After starting the update (from 0.6 to 0.7), when creating the backup folder, new `manifest.yml` is placed in backup folder, not in properly location. `terraform` directory is not created in properly location too.
File in ex. `backup_1593617417434`, `manifest.yaml` and `clusters/build/test/` directory are correct but not placed properly. 
Moreover, manifest file is overwritten in backup directory.
2. When user try to delete cluster, first time it's failover (with missing `manifest.yml` information). When user copy `manifest.yml` from backup folder, can execute delete cluster command without terraform state - remove it is only cluster directory and user lose state without deleting anything on Cloud.

**To Reproduce**
1. prepare 0.6 manifest:
```yaml
kind: epiphany-cluster
title: Epiphany cluster Config
provider: aws
name: default
specification:
  name: test
  prefix: prefix
  admin_user:
    name: ubuntu
    key_path: /home/vscode/.ssh/id_rsa
  cloud:
    use_public_ips: true
    region: eu-north-1
    credentials:
      key: AxxxD
      secret: Rxxx5
  components:
    kubernetes_master:
      count: 1
      subnets:
        - availability_zone: eu-north-1a
          address_pool: 10.1.2.0/24
    kubernetes_node:
      count: 1
      subnets:
        - availability_zone: eu-north-1a
          address_pool: 10.1.2.0/24
    postgresql:
      count: 0
    rabbitmq:
      count: 0
    load_balancer:
      count: 0
    logging:
      count: 0
    monitoring:
      count: 0
    kafka:
      count: 0
version: 0.6.0
```
2. execute `PYTHONPATH=`pwd` python3 cli/epicli.py apply -f clusters/cluster.yml --vault-password=Test1234!`
3. execute `PYTHONPATH=`pwd` python3 cli/epicli.py upgrade -b clusters/build/test/`
4. stop or wait
5. execute ex. `$ cat clusters/build/test/manifest.yml` <- there is no manifest
6. execute `PYTHONPATH=`pwd` python3 cli/epicli.py delete -b clusters/build/test/`

**Expected behavior**
`manifest.yaml` is in `clusters/build/test/` directory, `terraform` directory is in `clusters/build/test/` directory.

**OS (please complete the following information):**
 - OS: Ubuntu 16.04

**Cloud Environment (please complete the following information):**
 - Cloud Provider: AWS
