### ISSUE TITLE
[BUG] Certificate in Vault is also generated or copied even if flag in configuration tls_disable is set to true

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#1412]
**Describe the bug**
Certificate in Vault is also generated or copied even if flag in configuration tls_disable is set to true in Vault configuration.

**To Reproduce**
1. Create Vault config in Epiphany configuration, e.g:

```yaml
---
kind: configuration/vault
title: Vault Config
provider: aws
name: default
specification:
  vault_enabled: true
  tls_disable: true
```

2.  Execute `epicli apply ...` with your configuration file and settings from abov

**Expected behavior**
With flag tls_disable set to true part of code related to certificates should be skipped.

**Config files**
Shown above.

**OS (please complete the following information):**
 - OS: All

**Cloud Environment (please complete the following information):**
 - Cloud Provider: All

**Additional context**
No any additional context.
