### ISSUE TITLE
[FEATURE REQUEST] Set protocol for Vault only in one place in configuration

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#1413]
**Is your feature request related to a problem? Please describe.**
We should be able to set protocol for Vault only in one place, not like in the config below:

```yaml
---
kind: configuration/vault
title: Vault Config
provider: aws
name: default
specification:
  vault_enabled: true
  ...
  **tls_disable: true
  externalVaultAddr: http://external-vault:8200**
```

This can lead to inconsistency and confusing bugs.

**Describe the solution you'd like**
I would like to have protocol - http or https configured only in one place.

**Describe alternatives you've considered**

**Additional context**
No additional context.
