### ISSUE TITLE
[Spike]Research Rook/Ceph offline installation

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1457]
**Is your feature request related to a problem? Please describe.**
We don't have information how to install offline Rook managed Ceph cluster.

**Describe the solution you'd like**
We need after spike create document how to handle offline installation.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
Np additional context.

**Comment by willzhang** [comment]
we need rook offline!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by atsikham** [comment]
Based on previous tasks, additional articles and documentation ([requirements](https://rook.io/docs/rook/v1.8/pre-reqs.html)) I was able to perform [offline installation](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/CLUSTER.md#how-to-create-an-epiphany-cluster-on-existing-air-gapped-infrastructure) with [Helm](https://github.com/rook/rook/blob/v1.8.1/Documentation/helm-operator.md) in K8s cluster with 3 worker nodes and attached block devices.

For that purpose repository role was modified with additional files/images:

```
[files]
https://charts.rook.io/release/rook-ceph-v1.8.1.tgz

[images]
k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0
k8s.gcr.io/sig-storage/csi-resizer:v1.3.0
k8s.gcr.io/sig-storage/csi-snapshotter:v4.2.0
quay.io/ceph/ceph:v16.2.7
quay.io/cephcsi/cephcsi:v3.4.0
quay.io/csiaddons/volumereplication-operator:v0.1.0
rook/ceph:v1.8.1
```

Depending on version, these images can be found in chart's [values](https://github.com/rook/rook/blob/v1.8.1/deploy/charts/rook-ceph/values.yaml) or by following commands after [installation](https://github.com/rook/rook/blob/v1.8.1/Documentation/helm-operator.md) on the environment that has an internet access:

```bash
kubectl get pods -n rook-ceph -o jsonpath="{.items[*].spec.containers[*].image}" |\
tr -s '[[:space:]]' '\n' |\
sort |\
uniq -c

kubectl get pods -n rook-ceph -o jsonpath="{.items[*].spec.initContainers[*].image}" |tr -s '[[:space:]]' '\n' |sort |uniq -c 
```

When files are in Epiphany repository (should be enabled for testing purpose), it's necessary to [download](https://github.com/epiphany-platform/epiphany/blob/033d870aa2f16a46b5c6cf3b2e9c20a1d6d0c54a/ansible/playbooks/roles/download/tasks/download_file.yml) a chart and default chart values:

```bash
wget {{ repo_url }}/files/rook-ceph-v1.8.1.tgz # example: http://10.1.2.28/epirepo/files/rook-ceph-v1.8.1.tgz 

# also copy content from https://raw.githubusercontent.com/rook/rook/v1.8.1/deploy/charts/rook-ceph/values.yaml
```

Modify values:

**NOTE:** image_registry can be checked in `insecure_registries` of `/etc/docker/daemon.json`

```yaml
image:
  repository: {{ image_registry }}/rook/ceph
  tag: v1.8.1
...
cephcsi:
    image: {{ image_registry }}/quay.io/cephcsi/cephcsi:v3.4.0
  registrar:
    image: {{ image_registry }}/k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
  provisioner:
    image: {{ image_registry }}/k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0
  snapshotter:
    image: {{ image_registry }}/k8s.gcr.io/sig-storage/csi-snapshotter:v4.2.0
  attacher:
    image: {{ image_registry }}/k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
  resizer:
    image: {{ image_registry }}/k8s.gcr.io/sig-storage/csi-resizer:v1.3.0
```

Run installation:

**NOTE:** to verify installation attach block devices before this step

```bash
helm install --namespace rook-ceph --create-namespace -f values.yaml rook-ceph rook-ceph-v1.8.1.tgz --debug
```

Verify installation:

```bash
kubectl --namespace rook-ceph get pods -l "app=rook-ceph-operator"
kubectl --namespace rook-ceph get all
#NAME                                      READY   STATUS    RESTARTS   AGE
#pod/rook-ceph-operator-6588f57b4b-8p65c   1/1     Running   0          27m

#NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
#deployment.apps/rook-ceph-operator   1/1     1            1           27m

#NAME                                            DESIRED   CURRENT   READY   AGE
#replicaset.apps/rook-ceph-operator-6588f57b4b   1         1         1       27m

kubectl --namespace rook-ceph get deploy rook-ceph-operator -oyaml | grep image:
#        image: registry:5000/rook/ceph:v1.8.1

lsblk
#NAME                                                                                                  MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
#...
#nvme1n1                                                                                               259:2    0    8G  0 disk 
#└─ceph--f7ab8335--128e--4926--9ece--de24406090a5-osd--block--445fad4d--f1fe--4670--90a7--a3b24e52989b #253:0    0    8G  0 lvm  
```
