### ISSUE TITLE
[Spike] Research posible solutions and approaches to modularise epiphany

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1462]
**Is your feature request related to a problem? Please describe.**
We need to research and discuss possible solutions for epiphany modularization. 

Current monolithic architecture of epicli makes it hard to:
* make targeted upgrades (i.e.: I want to upgrade all but one component)
* test separate component
* allow 3rd party to provide new components

... etc. So we need to divide things into more modular way.

**Describe the solution you'd like**
My current thinking about it is: components of epiphany embedded in docker images. That would provide clear separation, possibility to have different runtime versions for different components, and also clear separation in chain of responsibilities. 

**Describe alternatives you've considered**

**Describe alternatives you've considered**
modular-cli document (mentioned later) does not consider dockerization so it should be assessed as well. 

**Additional context**
There is already some work done: 
* [modular-cli design-doc](https://github.com/epiphany-platform/epiphany/blob/develop/docs/design-docs/modular-cli/moduler-cli.md)
* [cli-ux design-doc components related sections](https://github.com/epiphany-platform/epiphany/blob/develop/docs/design-docs/cli/cli-ux.md#kubernetes-login)
* [old branch with modular-cli PoC](https://github.com/epiphany-platform/epiphany/tree/feature/modular-cli/src/)

**Comment by mkyc** [comment]
Question to be answered for each proposed solutions: 

* How much work does it require to package epicli to first module? 
* How much work does it require to package module CNS?
* How much work does it require to package module AKS/EKS? 
* How would be dependencies handled? 
* Would it be possible to install CNS module on Epiphany Kubernetes in version 0.4.4? 
* If I want to install CNS, how would dependencies be provided? 
* Lets assume that in version 0.8.0 of epiphany Postgresql is migrated to new component (managed not in epicli config). How would migration from 0.7.0 to 0.8.0 on existing environments be processed?
* Where would module store it’s configuration? 
* How would status of components be gathered by module? 
* How would modules pass variables between each other? 
* How would upstream module notify downstream that something changed in it’s values?

**Comment by mkyc** [comment]
While waiting for some more reviews of modularisation approaches comparison, I will focus on dependencies topic.

**Comment by mkyc** [comment]
# Dependencies problem statement

When thinking about dependencies in case of epiphany components there is few things to think about: 
* Those are not runtime dependencies, rather pre-requisites, 
* Component can have some strong requirement ie.: grafana v0.1.0 requires Prometheus > v0.2.0, 
* Component can have loose requirement ie.: postgresql v0.1.0 requires any type of cloud native storage to create PVC’s, 

That all means that when I do “e component install postgresql” it should go somehow like: 
* CLI command to install postgresql component
* CLI tool is checking component definition and finds selector looking somehow like `kind=storage, type=cloud-native`
* CLI tool is verifying if there is component satisfying selector installed in current environments
* CLI tool is verifying if installed component which satisfies selector has “applied” status. 
* If any of previous is not met, CLI tool should throw error

That means that we need to: 
* Mark command as actual “apply-type” and when it finishes without an error we should mark component as “applied”
* We need to catch component exit status
* We need to add labels to containers
* We need to add selector mechanism

## Selector for multiple components

Let’s assume there is component that has dependencies to two types of components ie.: to any kind of cloud native storage and any kind of sql database. Selector might look like:
```
requires:
  selectors:
  - kind: storage
    type: cloud-native
  - kind: database
    type: sql
```
For each element in list of selectors CLI tool would try to find at least one component satisfying all the values. 

## Depending on versions

When describing “strong” dependency to some component (ie.: name=aks) versioning is simple:
```
requires: 
  selectors:
  - name: aks
    version: 0.1.0
```
But when we want to depend on something loosely defined (ie.: any Kubernetes provider) than it becomes tricky. Lets say, that we have 3 components providing Kubernetes: 
-	AKS v0.1.0
-	EKS v0.2.1
-	OnPrem v0.9.4
All of them provide Kubernetes in version v1.17.x and we want our another component to depend on any of Kubernetes providers but we care about actual Kubernetes version they provide. Then selector would need to look something like:
```
requires:
  selectors:
  - kind: orchestrator
    type: kubernetes
    version-kubernetes: “>1.17”
```
That means that there would be requirement to have some convention for “version-…” labels.

**Comment by mkyc** [comment]
@seriva could you add description of what you did with those containers?

**Comment by seriva** [comment]
Yes here you can find a simple prototype for a simplified approach for structuring the container interface that the E cli tool would interact with:

https://github.com/seriva/component-cli

Some more research about how this interface should look still needs to be done + some research on how to properly layer the containers to minimize the container download size should still be done.

**Comment by mkyc** [comment]
so for first mentioned topic is #1475 and for second is #1478

**Comment by TolikT** [comment]
@mkyc for me this approach is clear, but implementation details aren't. Dokerized components solution seems to be applicable, but one question about config:
Why you use `version-kubernetes` instead of just a `version` and want to create some convention for this? 
```
requires:
  selectors:
  - kind: orchestrator
    type: kubernetes
    version-kubernetes: “>1.17”
```

**Comment by mkyc** [comment]
@TolikT Basically there will be need to rely on version of software some module provides. So as described in example, let’s assume that there would be 3 modules providing Kubernetes. 

First one - AKS - would be described in with labels: 
```
labels: 
  name: aks
  kind: orchestrator
  type: kubernetes
  version-kubernetes: “1.16.1”
  version-etcd: “3.2.24”
```

Second would be EKS described somehow like:
```
labels: 
  name: eks
  kind: orchestrator
  type: kubernetes
  version-kubernetes: “1.15.2”
  version-etcd: “3.1.5”
```

And third would be our on-prem module with following labels: 

```
labels: 
  name: on-prem
  kind: orchestrator
  type: kubernetes
  version-kubernetes: “1.18.6”
  version-etcd: “3.4.10”
```

Now let’s assume that I need to use **any** Kubernetes module as long it is **newer then** 1.16.x and etcd **up to** 3.4.x. That means that I want to pass to my requires section something like: 

```
requires:
  selectors:
  - kind: orchestrator
    type: kubernetes
    version-kubernetes: “>1.16”
    version-etcd: “<3.4”
```

That means that for fields not starting with `version-` there would be exact matching used, but for fields starting with `version-` there would be need to match ranges because you usually want **range** of versions in your dependencies. 

I’m also not happiest person to mix things like this, but I do not want to make this `selectors` section too complicated in yaml. 

Communication between modules is still not clearly defined.

**Comment by TolikT** [comment]
@mkyc did you consider usage of a `version(s)` dictionary instead? With existing of some default versions and defined list of possible software for each component.

**Comment by mkyc** [comment]
@TolikT Nope, because I was afraid that we would end up with something like:

```
requires:
  selectors:
  - kind: orchestrator
    type: kubernetes
    versions: 
    - kubernetes: 
      - "1.16.0”
      - "1.16.1”
      - "1.16.2”
      - "1.16.3”
      - "1.16.4”
      - "1.16.5”
      - "1.16.6”
      - "1.16.7”
      - "1.16.8”
      - "1.17.0”
      - "1.17.1”
      - "1.17.2”
      - "1.17.3”
      - "1.17.4”
...
```

But in fact I'm very open for suggestions. I would like to avoid convention in here, so if you have some good idea please share.
