### ISSUE TITLE
[FEATURE REQUEST] Add support for Azure availability sets

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1543]
**Is your feature request related to a problem? Please describe.**
We would like to have possibility to create availability-set for Azure using Epiphany in order to have a group with two or more virtual machines in the same Data Center. This ensures that at least one of the virtual machines hosted on Azure will be available if something happens. This configuration offers 99.95% SLA. 

**Describe the solution you'd like**
We would like to have section in cluster yaml file with the availability-set for all components, for example:: 
```
kind: infrastructure/availability-set
name: kube-node-availability-set
provider: azure
specification:
  name: kube-node-availability-set
  platform_fault_domain_count: 2
  platform_update_domain_count: 5
  managed: 'true'
```
**Describe alternatives you've considered**

**Additional context**
This task is to manage already existing PR #1411
