### ISSUE TITLE
[FEATURE REQUEST] update network security rule to open port 6443

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1616]
**Is your feature request related to a problem? Please describe.**
Currently even with obtained locally kubeconf file we are unable to access kubernetes cluster because there is no access to port 6443 on master node

**Describe the solution you'd like**
We need to open port 6443 to access Kubernetes API. 

**Describe alternatives you've considered**
SSH tunnelling would be another option to consider. 

**Additional context**
That is required to start work with managed kubernetes services. 
External code example doing this is [here](https://github.com/mkyc/k8s-rook-ceph/blob/master/Makefile#L43-L55) and [here](https://github.com/mkyc/k8s-rook-ceph/blob/master/Makefile#L109-L112)

**Comment by mkyc** [comment]
Consider opening port 6443 just for short period of time when we are interacting with Kubernetes API.

**Comment by rpudlowski93** [comment]
In case of AKS which is managed service, developer doesn't have access to any master node and only API server is exposed by default by Azure for communication with cluster. 

In order to be more secure we can limit access to cluster using authorized IP ranges, enable Role-Based Access Control or create private cluster and grant access to the private cluster using for example bastion host. 

Moreover, In case of AKS, we use kubeconfig file for communication and we use port 443, not 6443. 443 is secure and we should focus on secure storing the kubeconf, not security group and ports - in my opinion. 

AKS: 
```
$ kubectl cluster-info
Kubernetes master is running at https://kubernetes_master:443
```

Nice to know: 
- 1194 and 9000 port is for tunneled secure communication between the **nodes** and the **control plane**.
- 443 TCP - access to API server


Finally, we want to use always kubectl locally, even during creation of "standard" kubernetes cluster in epiphany so in this case we need to open the port - 6443.

**Comment by seriva** [comment]
Instead of opening 6443 for opening  managing "standard" kubernetes cluster lets use an SSH tunnel forwarding 6443 to the master machine because:

1: Security, opening 6443 might not be the best since we need to manage the security for these K8s clusters ourselves unlike the AKS etc.
2: The kubeconf generate by our "standard" kubernetes only works for the private IPs or localhost so to use a secure connection with TLS we need to probably regenerate this or setup some VPN from Epicli which will be a pain for the cloud installs we can do.

I did not find any easy way or plugin todo this straight with kubectl but with Ansible setting up and using this tunneling is pretty straight forward. We need to change the IP inside the kubeconf to point to the localhost:

![image](https://user-images.githubusercontent.com/11056665/92608036-27442080-f2b5-11ea-8aa6-6a2fcef7ad6c.png)

And then we can do something like this for actually executing the local kubectl commands against our the master node with the modified kubeconf:

```YAML
- name: kubectl command through SSH tunnel POC
  hosts: 127.0.0.1
  connection: local
  vars:
    - kube_api_port: 6443
    - kube_api_host: 1.2.3.4
    - kube_config: /workspaces/epiphany/core/src/epicli/clusters/build/clustername/admin.conf
    - ssh_user: operations
    - ssh_key: /home/vscode/ssh/id_rsa_epi
    - kubectl_command: kubectl get pods --all-namespaces
  handlers:
    - name: stop ssh tunnel
      shell: ps -ef | grep -iE -- "ss[h].*{{kube_api_port}}" | awk '{print $2}' | xargs kill -9
  tasks:
    - name: clear any existing ssh tunnel
      shell: ps -ef | grep -iE -- "ss[h].*{{kube_api_port}}" | awk '{print $2}' | xargs kill -9
      ignore_errors: yes

    - name: start ssh tunnel
      shell: nohup ssh -N {{ssh_user}}@{{kube_api_host}} -i {{ssh_key}} -L {{kube_api_port}}:localhost:{{kube_api_port}} &
      notify: stop ssh tunnel

    - name: kubectl command
      environment:
        KUBECONFIG: "{{kube_config}}"
      shell: ps -eo pcpu,user,args | {{kubectl_command}}
      register: ps

    - name: kubectl command output
      debug: var=ps.stdout_lines
```

**Comment by atsikham** [comment]
I'm thinking about stability and persistence of ssh port forwarding for long running processes, probably in future we will have to handle related edge cases. IMO opening a port for a while is better, but it definitely should be closed after deployment if not required to be open.

**Comment by seriva** [comment]
@atsikham Opening and closing this port before and after Ansible run is an option. Preferably using AzureCLI and Boto would be the easiest option from Python code:

https://docs.microsoft.com/en-us/cli/azure/network/nsg/rule?view=azure-cli-latest
https://boto3.amazonaws.com/v1/documentation/api/1.9.42/guide/ec2-example-security-group.html

Terraform would be another option but that will be more complicated for sure. Just not sure how Terraform will react if we add and remove these rules from a state perspevtive.

**Comment by sk4zuzu** [comment]
IMO I think using ssh tunnels or vpns do not add any significant security value. Kubernetes authentication is client-certificate based, that means that you need to have a specific private key to access the API and this is fundamentally just the same mechanism ssh uses in key based authentication. The great example of this is for example in GKE or AKS, they expose the port and then you have to get the correct kubeconfig file using console tools. If they don't really have problem with that I don't think we should. :+1:

**Comment by to-bar** [comment]
I'm not a fun of this command:
```
    - name: clear any existing ssh tunnel
      shell: ps -ef | grep -iE -- "ss[h].*{{kube_api_port}}" | awk '{print $2}' | xargs kill -9
```
it could kill too much.
I would prefer more robust solution, maybe with named sockets: https://mpharrigan.com/2016/05/17/background-ssh.html

However, I'm afraid of scenario when network connection was interrupted, then the tunnel probably would be closed (didn't test) and we would lose the `retry` Ansible's functionality. Second thing is that from developer (and QA) perspective it's proffered to have the same logic/path for `kubectl` regardless of K8s type. Adding tunneling would require one path for hosted K8s and another for cloud managed service.

In K8s docs 6443 is called `Secure Port`:
https://kubernetes.io/docs/reference/access-authn-authz/controlling-access/#api-server-ports-and-ips

Maybe we could expose 6443 on public IP only for installation/maintenance time (later operators could SSH to master and operate as so far)? Or allow connections dynamically (firewall) only from trusted sources - from IP of host with epicli container?

I see two options for now:
1) allow connections from outside the cluster - add public IPs to cert SANs as we had previously + replace IP in kubeconfig from private to public + add rule on firewall / NSG to open the API server port - this is preffered
2) use SSH tunneling - adds complexity and could be error prone

In the future I think it would be good to have Bastion.
For strongly secured clusters I think one will not use public IPs so I vote for 1)

**Comment by mkyc** [comment]
I vote for port opening.

**Comment by seriva** [comment]
Just additional comment, temporary port opening will be adding and removing that rule before and running the Terraform command before and after Ansible run. Doing that with AzureCLI/Boto messes up state.

**Comment by toszo** [comment]
@seriva, @mkyc, @to-bar The only scenario where I'm fine with opening the port is that **we have only public IPs**, meaning clusters peered (that use private ips) will not create public IP and expose 6443.

**Comment by mkyc** [comment]
That is also my understanding. If we can communicate with Kubernetes API over secured channel, we are not going to open port to the world.

**Comment by seriva** [comment]
Small improvement over the tunnel approach we might consider instead of the port opening. Usage of small utility to called [autossh](https://linux.die.net/man/1/autossh) which we need to add to the Epicli container. This will basically monitor an SSH connection and re-establish in case of issues or dropped connections. With a simple additional script it allows us to kill only the SSH connection spawned/maintained by it targeted to a certain host. I would see opening/closing the SSH tunnel connection at the start and end of our ansible runs.  autossh will maintain the connection while these are running. If the kubectl commands will fail Ansible retry should be working ok in this instance.

POC:

```shell
  if [ "$1" = "--kill" ]; then
    ps aux | 
    grep -P "(/usr/bin/ssh|/usr/lib/autossh/autossh)\s.*$2" |
    awk '{print $2}' |
    xargs -r kill
  else
    $(which autossh) "$@"
  fi
```

```YAML
- name: kubectl command through SSH tunnel POC
  hosts: 127.0.0.1
  connection: local
  vars:
    - kube_api_port: 6443
    - kube_api_host: 1.2.3.4
    - kube_config: /workspaces/epiphany/core/src/epicli/clusters/build/azureu/admintunnel.conf
    - ssh_user: operations
    - ssh_key: /home/vscode/ssh/id_rsa_epi
    - kubectl_command: kubectl get pods --all-namespaces
  handlers:
    - name: stop ssh tunnel
      shell: ./tunnel.sh --kill {{kube_api_host}}
  tasks:
    - name: clear any existing ssh tunnel
      shell: ./tunnel.sh --kill {{kube_api_host}}

    - name: start ssh tunnel
      shell: ./tunnel.sh -f -N -M 0 -o "ServerAliveInterval 30" -o "ServerAliveCountMax 5" -4 -L  {{kube_api_port}}:localhost:{{kube_api_port}} -i {{ssh_key}} {{ssh_user}}@{{kube_api_host}} -4
      notify: stop ssh tunnel

    - name: kubectl command
      environment:
        KUBECONFIG: "{{kube_config}}"
      shell: ps -eo pcpu,user,args | {{kubectl_command}}
      register: ps

    - name: kubectl command output
      debug: var=ps.stdout_lines
```
