### ISSUE TITLE
[BUG] Logstash installation fails on Azure RedHat environments

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#1632]
**Describe the bug**
Logstash installation error occured in task `logstash : Ensure Logstash is disabled` on Azure RedHat environments.
Logstash service could not be found.

**To Reproduce**
Steps to reproduce the bug:
1. Deploy a new cluster from develop branch with at least 1 logging vm enabled (configuration given below):  `epicli apply -f test.yml`

**Config files**

```yaml
---
kind: epiphany-cluster
name: default
provider: azure
specification:
  admin_user:
    key_path: /path/to/id_rsa
    name: operations
  cloud:
    region: West Europe
    subscription_name: xxx
    use_public_ips: true
    use_service_principal: true   
  components:
    kafka:
      count: 0
      machine: kafka-machine-rhel
    kubernetes_master:
      count: 1
      machine: kubernetes-master-machine-rhel
    kubernetes_node:
      count: 1
      machine: kubernetes-node-machine-rhel
    load_balancer:
      count: 0
      machine: lb-machine-rhel  
    logging:
      count: 1
      machine: logging-machine-rhel
    monitoring:
      count: 0
      machine: monitoring-machine-rhel
    postgresql:
      count: 0
      machine: postgresql-machine-rhel
    rabbitmq:
      count: 0
      machine: rabbitmq-machine-rhel
    ignite:
      count: 0
      machine: ignite-machine-rhel
    opendistro_for_elasticsearch:
      count: 0
      machine:  opendistro-machine-rhel
  name: logstashtest
  prefix: 'qa'
title: Epiphany cluster Config
---
kind: infrastructure/virtual-machine
name: kubernetes-master-machine-rhel
provider: azure
based_on: kubernetes-master-machine
specification:
  storage_image_reference:
    publisher: RedHat
    offer: RHEL
    sku: 7-RAW
    version: "7.7.2019090418"
---
kind: infrastructure/virtual-machine
name: kubernetes-node-machine-rhel
provider: azure
based_on: kubernetes-node-machine
specification:
  storage_image_reference:
    publisher: RedHat
    offer: RHEL
    sku: 7-RAW
    version: "7.7.2019090418"
---
kind: infrastructure/virtual-machine
name: logging-machine-rhel
provider: azure
based_on: logging-machine
specification:
  storage_image_reference:
    publisher: RedHat
    offer: RHEL
    sku: 7-RAW
    version: "7.7.2019090418"
---
kind: configuration/kubernetes-master
name: default
provider: azure
specification:
  advanced:
    networking:
      plugin: flannel
---
kind: configuration/feature-mapping
title: "Feature mapping to roles"
name: default
provider: azure
specification:
  roles_mapping:
    logging:
      - logging
      - logstash
      - kibana
      - node-exporter
      - filebeat
      - firewall
```

**Expected behavior**
The cluster has been deployed successfully.

**OS (please complete the following information):**
 - OS: [RHEL]

**Cloud Environment (please complete the following information):**
 - Cloud Provider [MS Azure]

**Additional context**
Log:
```2020-09-09T13:13:18.9771335Z[38;21m13:13:18 INFO cli.engine.ansible.AnsibleCommand - TASK [logstash : Ensure Logstash is disabled] **********************************
2020-09-09T13:13:22.2204789Z[31;21m13:13:22 ERROR cli.engine.ansible.AnsibleCommand - fatal: [ci-devazurrhelflannel-logging-vm-0]: FAILED! => {"changed": false, "msg": "Could not find the requested service logstash: host"}
```

`[operations@ci-devazurrhelflannel-logging-vm-0 ~]$ systemctl status logstash`
`Unit logstash.service could not be found.`
