### ISSUE TITLE
[BUG] Upgrade process fails on Ubuntu with package downgrade

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/epiphany#1659]
**Describe the bug**
Upgrade fails on Ubuntu. Related log part:

```text
{"asctime": "15:54:02", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": "TASK [upgrade : k8s/install | Get information about installed packages as facts] ********************************************************"}
{"asctime": "15:54:05", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": "ok: [ec2-3-95-156-60.compute-1.amazonaws.com]"}
{"asctime": "15:54:05", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": ""}
{"asctime": "15:54:05", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": "TASK [upgrade : k8s/install | Include unhold packages task] *****************************************************************************"}
{"asctime": "15:54:05", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": "included: /workspaces/epiphany/core/src/epicli/clusters/rabbit/build/rabbit/ansible/roles/upgrade/tasks/kubernetes/Debian/unhold-packages.yml for ec2-3-95-156-60.compute-1.amazonaws.com"}
{"asctime": "15:54:05", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": ""}
{"asctime": "15:54:05", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": "TASK [upgrade : k8s/install | Unhold packages: kubelet, kubectl, kubernetes-cni] ********************************************************"}
{"asctime": "15:54:08", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": "changed: [ec2-3-95-156-60.compute-1.amazonaws.com]"}
{"asctime": "15:54:08", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": ""}
{"asctime": "15:54:08", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": "TASK [upgrade : k8s/install | Remove newer Debian packages installed as dependencies if they exist] *************************************"}
{"asctime": "15:54:10", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": "ok: [ec2-3-95-156-60.compute-1.amazonaws.com]"}
{"asctime": "15:54:10", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": ""}
{"asctime": "15:54:10", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": "TASK [upgrade : k8s/install | Install kubernetes-cni 0.8.6, kubelet 1.18.6, kubectl 1.18.6 packages for Debian family] ******************"}
{"asctime": "15:54:14", "levelname": "ERROR", "name": "cli.engine.ansible.AnsibleCommand", "message": "fatal: [ec2-3-95-156-60.compute-1.amazonaws.com]: FAILED! => {\"cache_update_time\": 1600185254, \"cache_updated\": true, \"changed\": false, \"msg\": \"'/usr/bin/apt-get -y -o \\\"Dpkg::Options::=--force-confdef\\\" -o \\\"Dpkg::Options::=--force-confold\\\"      install 'kubernetes-cni=0.8.6-00'' failed: E: Packages were downgraded and -y was used without --allow-downgrades.\\n\", \"rc\": 100, \"stderr\": \"E: Packages were downgraded and -y was used without --allow-downgrades.\\n\", \"stderr_lines\": [\"E: Packages were downgraded and -y was used without --allow-downgrades.\"], \"stdout\": \"Reading package lists...\\nBuilding dependency tree...\\nReading state information...\\nThe following packages will be DOWNGRADED:\\n  kubernetes-cni\\n0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 19 not upgraded.\\n\", \"stdout_lines\": [\"Reading package lists...\", \"Building dependency tree...\", \"Reading state information...\", \"The following packages will be DOWNGRADED:\", \"  kubernetes-cni\", \"0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 19 not upgraded.\"]}"}
{"asctime": "15:54:14", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": ""}
{"asctime": "15:54:14", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": "PLAY RECAP ******************************************************************************************************************************"}
{"asctime": "15:54:14", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": "ec2-18-207-223-69.compute-1.amazonaws.com : ok=35   changed=0    unreachable=0    failed=0    skipped=19   rescued=0    ignored=0   "}
{"asctime": "15:54:14", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": "ec2-184-72-127-244.compute-1.amazonaws.com : ok=35   changed=0    unreachable=0    failed=0    skipped=19   rescued=0    ignored=0   "}
{"asctime": "15:54:14", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": "ec2-184-72-195-93.compute-1.amazonaws.com : ok=28   changed=0    unreachable=0    failed=0    skipped=17   rescued=0    ignored=0   "}
{"asctime": "15:54:14", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": "ec2-3-95-156-60.compute-1.amazonaws.com : ok=93   changed=4    unreachable=0    failed=1    skipped=33   rescued=0    ignored=0   "}
{"asctime": "15:54:14", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": "ec2-54-234-113-113.compute-1.amazonaws.com : ok=28   changed=0    unreachable=0    failed=0    skipped=17   rescued=0    ignored=0   "}
{"asctime": "15:54:14", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": ""}
{"asctime": "15:54:14", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleRunner", "message": "Run done in 734411ms"}
{"asctime": "15:54:14", "levelname": "INFO", "name": "cli.engine.UpgradeEngine", "message": "Run done in 734421ms"}
{"asctime": "15:54:14", "levelname": "ERROR", "name": "epicli", "message": "Error running: \"ansible-playbook -i /workspaces/epiphany/core/src/epicli/clusters/rabbit/build/rabbit/inventory /workspaces/epiphany/core/src/epicli/clusters/rabbit/build/rabbit/ansible/upgrade.yml\""}
{"asctime": "15:54:17", "levelname": "INFO", "name": "dump_debug_info", "message": "Error dump has been written to: /workspaces/epiphany/core/src/epicli/epicli_error_20200915-155414.dump"}
{"asctime": "15:54:17", "levelname": "WARNING", "name": "dump_debug_info", "message": "This dump might contain sensitive information. Check before sharing."}
```

**To Reproduce**
1. Deploy a k8s cluster from `develop`
2. Upgrade a k8s cluster with `develop` version 
3. Check results

**Expected behavior**
Successful upgrade.

**Config files**

```yaml
---
kind: configuration/shared-config
title: Shared configuration that will be visible to all roles
name: default
provider: aws
specification:
  custom_repository_url: ''
  custom_image_registry_address: ''
  download_directory: /tmp
  vault_location: ''
  vault_tmp_file_location: SET_BY_AUTOMATION
  use_ha_control_plane: true
  promote_to_ha: false
version: 0.7.1
---
kind: epiphany-cluster
title: Epiphany cluster Config
provider: aws
name: default
specification:
  name: rabbit
  prefix: atsikham
  admin_user:
    name: ubuntu
    key_path: /home/vscode/.ssh/id_rsa
  cloud:
    use_public_ips: true
    credentials:
      key: xxx
      secret: xxx
    region: us-east-1
  components:
    kubernetes_master:
      count: 3
      subnets:
        - availability_zone: us-east-1a
          address_pool: 10.1.2.0/24
    kubernetes_node:
      count: 2
      subnets:
        - availability_zone: us-east-1a
          address_pool: 10.1.2.0/24
    logging:
      count: 0
    monitoring:
      count: 0
    kafka:
      count: 0
    postgresql:
      count: 0
    load_balancer:
      count: 0
    rabbitmq:
      count: 0
version: 0.7.1
```

**OS (please complete the following information):**
 - OS: Ubuntu

**Cloud Environment (please complete the following information):**
 - Cloud Provider AWS
The issue is not cloud-specific.

**Additional context**
Checked the current version of `kubernetes-cni` dist package on one of failed hosts, it's `0.8.7-00`
