### ISSUE TITLE
[BUG] Filebeat multiline support - truncated single quotes in the regular expression pattern

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#1669]
**Describe the bug**
Epiphany truncates single quotes from the regular expression pattern for multiline support, which can lead to incorrect log aggregation.

**To Reproduce**
Steps to reproduce the bug:
1. Deploy a new cluster from develop branch with the configuration given below: `epicli apply -f test.yml`

**Config files**

```yaml
---
kind: configuration/filebeat
title: Filebeat
name: default
provider: azure
specification:
  filebeat_version: "7.8.1"
  postgresql_input:
    multiline:
      pattern: '^\d{4}-\d{2}-\d{2} '
      negate: true
      match: after
  docker_input:
    multiline:
      pattern: '([12]\d{3}[- \/.](0[1-9]|1[0-2])[- \/.](0[1-9]|[12]\d|3[01]))|(0[1-9]|1[012])[- \/.](0[1-9]|[12][0-9]|3[01])[- \/.]\d\d'
      negate: true
      match: after
  common_input:
    multiline:
      pattern: '^\d{4}-\d{2}-\d{2}'
      negate: true
      match: after
```

**Expected behavior**
The file `/etc/filebeat/filebeat.yml` contains a valid pattern, exactly as defined in the configuration.

**Actual behavior**
There are truncated single quotes in the manifest file for docker and common input:
```yaml
---
kind: configuration/filebeat
title: Filebeat
name: default
specification:
  filebeat_version: 7.8.1
  postgresql_input:
    multiline:
      pattern: '^\d{4}-\d{2}-\d{2} '
      negate: true
      match: after
  docker_input:
    multiline:
      pattern: ([12]\d{3}[- \/.](0[1-9]|1[0-2])[- \/.](0[1-9]|[12]\d|3[01]))|(0[1-9]|1[012])[-
        \/.](0[1-9]|[12][0-9]|3[01])[- \/.]\d\d
      negate: true
      match: after
  common_input:
    multiline:
      pattern: ^\d{4}-\d{2}-\d{2}
      negate: true
      match: after
version: 0.7.1
provider: azure
```

There are no single quotes at all in `/etc/filebeat/filebeat.yml`.
```
# -------------------------- PostgreSQL input --------------------------

# Filebeat postgresql module doesn't support custom log_line_prefix (without patching), see https://discuss.elastic.co/t/filebeats-with-postgresql-module-custom-log-line-prefix/204457
# Dedicated configuration to handle log messages spanning multiple lines.

- type: log
  enabled: true
  paths:
    - /var/log/postgresql/*.log*
  exclude_files: [".gz$"]
  multiline:
    pattern: ^\d{4}-\d{2}-\d{2}
    negate: True
    match: after
```

**OS (please complete the following information):**
 - OS: [all]

**Cloud Environment (please complete the following information):**
 - Cloud Provider [all]

The [documentation ](https://www.elastic.co/guide/en/beats/filebeat/current/multiline-examples.html)shows the correct configuration of the `filebeat.yml` file.

**Comment by to-bar** [comment]
Fix tested, single quotes are preserved. The default configuration (`specification.postgresql_input`) works fine.

I recommend adding schema validation for `configuration/filebeat` kind in the future to ensure `multiline.pattern` is always quoted, like:
```
multiline:
  type: object
  properties:
    pattern:
      type: string
      pattern: "^'.+'$"
```
