### ISSUE TITLE
[BACKPORT] Ability to use "long lasting" Kubernetes certificates - 0.7.x backport

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#1680]
**Is your feature request related to a problem?**
By design Kubernetes assumes all newly created certificates have expiration time set to 1 year. There is really no automatic way to overcome that and modify expiration time.

**Describe the solution you'd like**
This issue is already fixed and implemented in task #1302 and we would like to backport it to 0.7.x and test it.

```
---
kind: configuration/kubernetes-master
title: "Kubernetes Master Config"
name: default
provider: azure
specification:
  advanced:
    certificates:
      location: /etc/kubernetes/pki
      expiration_days: 800
      renew: false

```

Recommended tests: 
- single machine, single-master and HA installations
- parameter values: renew: true, renew: false with different periods, including default
- new installations using running epicli apply for the second time after changing parameters

**Describe alternatives you've considered**
it's possible to renew certs by kubeadm manually: kubeadm alpha certs renew apiserver, but we don't want to do it manually
`kubeadm alpha certs renew apiserver
`

**Additional context**
These changes can be modified to work without openssl_* modules, with shell.
