### ISSUE TITLE
[BUG] Vault fails to install after changing helm to use localhost

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#1729]
**Describe the bug**
Vault installation fails after recent changes to `helm` and `kubectl` now executed locally.

**To Reproduce**
Deploy a new cluster from develop branch with the configuration given below: `epicli apply -f test.yml`
**Config files**

```yaml
---
kind: configuration/vault
title: Vault Config
name: default
provider: aws
specification:
  vault_enabled: true
```

**Expected behavior**
The cluster with Vault enabled has been deployed successfully

**OS (please complete the following information):**
 - OS: [all]

**Cloud Environment (please complete the following information):**
 - Cloud Provider [all]

**Additional context**
The installation fails on `TASK [vault : Run configuration script]` returning an error `ERROR: There was an error during checking if Vault Agent Helm Chart is already installed. Exit status: 127"`.
Command called: `helm list | grep vault;` but now there is no `helm` on kubernetes master vm.
The role should be refactored according to the latest changes to use **local `helm`** and **local `kubectl`**.
