### ISSUE TITLE
[BUG] Upgrade doesn't work with ERROR epicli - No such attribute: cloud

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/epiphany#1741]
**Describe the bug**
Upgrade process finishes with an error

```text
ERROR epicli - No such attribute: cloud
```

**To Reproduce**
1. Deploy v0.6 cluster on Azure.
2. Run upgrade from `develop` branch.

**Expected behavior**
Successful upgrade.

**Config files**
```yaml
---
kind: configuration/shared-config
title: Shared configuration that will be visible to all roles
name: default
provider: azure
specification:
  custom_repository_url: ''
  custom_image_registry_address: ''
  download_directory: /tmp
  vault_location: ''
  vault_tmp_file_location: SET_BY_AUTOMATION
  use_ha_control_plane: true
  promote_to_ha: false
version: 0.7.1
---
kind: epiphany-cluster
title: Epiphany cluster Config
provider: azure
name: odfe
specification:
  prefix: atsikham
  name: certs
  admin_user:
    name: ubuntu
    key_path: /home/vscode/.ssh/id_rsa
  cloud:
    subscription_name: <subscription>
    use_public_ips: true
    use_service_principal: false
    region: West Europe
  components:
    kubernetes_master:
      count: 1
    kubernetes_node:
      count: 0
    logging:
      count: 0
    monitoring:
      count: 0
    kafka:
      count: 0
    postgresql:
      count: 0
    load_balancer:
      count: 0
    rabbitmq:
      count: 0
    ignite:
      count: 0
    opendistro_for_elasticsearch:
      count: 1
    single_machine:
      count: 0
version: 0.7.1
```

**OS (please complete the following information):**
 - OS: Ubuntu, but it doesn't matter

**Cloud Environment (please complete the following information):**
 - Cloud Provider: Azure, but all affected

**Additional context**
There is such piece of code in `AnsibleInventoryUpgrade.py`:

```python
# re-constructure cluster model with all data necessary to run required upgrade rolls
        self.cluster_model = dict_to_objdict({
            'provider': 'any',
            'specification': {
                'admin_user': {
                    'name': loaded_inventory.groups['all'].vars['ansible_user'],
                    'key_path': loaded_inventory.groups['all'].vars['ansible_ssh_private_key_file']
                }
            }
        })
```
That model is used then in upgrade process with no success, see related [changes](https://github.com/epiphany-platform/epiphany/blame/develop/core/src/epicli/cli/engine/ansible/AnsibleVarsGenerator.py#L124).
