### ISSUE TITLE
[BUG] [v0.7] Grafana dashboard deployment failed

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#1777]
**Describe the bug**
Downloading Grafana dashboard from public repository failed during `epicli apply`
```
{"asctime": "07:23:47", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": "TASK [grafana : download grafana dashboard from grafana.net to local directory] **********************************************************"}
{"asctime": "07:23:47", "levelname": "ERROR", "name": "cli.engine.ansible.AnsibleCommand", "message": "FAILED - RETRYING: download grafana dashboard from grafana.net to local directory (5 retries left)."}
{"asctime": "07:23:49", "levelname": "ERROR", "name": "cli.engine.ansible.AnsibleCommand", "message": "FAILED - RETRYING: download grafana dashboard from grafana.net to local directory (4 retries left)."}
{"asctime": "07:23:52", "levelname": "ERROR", "name": "cli.engine.ansible.AnsibleCommand", "message": "FAILED - RETRYING: download grafana dashboard from grafana.net to local directory (3 retries left)."}
{"asctime": "07:23:54", "levelname": "ERROR", "name": "cli.engine.ansible.AnsibleCommand", "message": "FAILED - RETRYING: download grafana dashboard from grafana.net to local directory (2 retries left)."}
{"asctime": "07:23:56", "levelname": "ERROR", "name": "cli.engine.ansible.AnsibleCommand", "message": "FAILED - RETRYING: download grafana dashboard from grafana.net to local directory (1 retries left)."}
{"asctime": "07:23:58", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": "failed: [ec2-18-193-113-174.eu-central-1.compute.amazonaws.com -> localhost] (item={'dashboard_id': '4271', 'revision_id': '3', 'datasource': 'Prometheus'}) => {\"ansible_loop_var\": \"item\", \"attempts\": 5, \"changed\": false, \"cmd\": \"curl --fail --compressed https://grafana.com/api/dashboards/4271/revisions/3/download -o /tmp/ansible.a_imubu9/4271.json\", \"item\": {\"dashboard_id\": \"4271\", \"datasource\": \"Prometheus\", \"revision_id\": \"3\"}, \"msg\": \"[Errno 2] No such file or directory: 'curl': 'curl'\", \"rc\": 2}"}
{"asctime": "07:23:58", "levelname": "INFO", "name": "cli.engine.ansible.AnsibleCommand", "message": ""}
```
**To Reproduce**
1. Provide Grafana configuration like below
2. epicli apply

**Expected behavior**
1. Successfull download of specified Grafana dashboard.
2. The dashboard should be imported into Grafana dashboards.

**Config files**
Sample config:
```yaml
---
kind: configuration/grafana
title: Grafana
name: default
specification:
  version: 6.2.5
  grafana_logs_dir: /var/log/grafana
  grafana_data_dir: /var/lib/grafana
  grafana_address: 0.0.0.0
  grafana_port: 3000
  grafana_use_provisioning: true
  grafana_provisioning_synced: false
  grafana_url: https://0.0.0.0:3000
  grafana_server:
    protocol: https
    enforce_domain: false
    socket: ''
    cert_key: /etc/grafana/ssl/grafana_key.key
    cert_file: /etc/grafana/ssl/grafana_cert.pem
    enable_gzip: false
    static_root_path: public
    router_logging: false
  grafana_security:
    admin_user: x
    admin_password: x
  grafana_database:
    type: sqlite3
  grafana_dashboards:
    - dashboard_id: '4271'
      revision_id: '3'
      datasource: 'Prometheus'
  grafana_dashboards_dir: dashboards
  grafana_welcome_email_on_sign_up: false
  grafana_users:
    allow_sign_up: false
    auto_assign_org_role: Viewer
    default_theme: dark
  grafana_auth: {}
  grafana_ldap: {}
  grafana_session: {}
  grafana_analytics: {}
  grafana_smtp: {}
  grafana_alerting:
    execute_alerts: true
  grafana_log:
  grafana_metrics: {}
  grafana_tracing: {}
  grafana_snapshots: {}
  grafana_image_storage: {}
  grafana_plugins: []
  grafana_alert_notifications: []
  grafana_datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    basicAuth: false
    basicAuthUser: ''
    basicAuthPassword: ''
    isDefault: true
    editable: true
    jsonData:
      tlsAuth: false
      tlsAuthWithCACert: false
      tlsSkipVerify: true

  # API keys to configure
  grafana_api_keys: []
  grafana_logging:
    log_rotate: true
    daily_rotate: true
    max_days: 7
version: 0.6.1
provider: aws
```

**OS (please complete the following information):**
 - Tested on RHEL

**Cloud Environment (please complete the following information):**
- Tested on AWS

**Additional context**
curl has been added to dockerfile in 0.8.0rc1.
