### ISSUE TITLE
[BACKPORT] [v0.5] Epicli does not create PostgreSQL SET_BY_AUTOMATION values correctly

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#1809]
We need to back port issue #1372 (fixed in v0.7.0) to v0.5 branch.

**Comment by przemyslavic** [comment]
Tested configurations:
:white_check_mark: `epicli init -p aws -n testaws --full`
:white_check_mark: `epicli init -p azure -n testazure --full`

Output:
```yaml
...
    - name: RESOURCE USAGE (except WAL)
      subgroups:
      - name: Kernel Resource Usage
        parameters:
        - name: shared_preload_libraries
          value: AUTOCONFIGURED
          comment: set by automation
...
```
:white_check_mark: `epicli apply` with PostgreSQL vms
No problems encountered :heavy_check_mark:
