### ISSUE TITLE
[BACKPORT] [v0.6] Epicli does not create PostgreSQL SET_BY_AUTOMATION values correctly

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#1810]
We need to back port issue #1372 (fixed in v0.7.0) to v0.6 branch.

**Comment by przemyslavic** [comment]
Tested configurations:
:white_check_mark: `epicli init -p aws -n testaws --full`
:white_check_mark: `epicli init -p azure -n testazure --full`
:white_check_mark: `epicli init -p any -n testany --full`

Output:
```yaml
...
    - name: RESOURCE USAGE (except WAL)
      subgroups:
      - name: Kernel Resource Usage
        parameters:
        - name: shared_preload_libraries
          value: AUTOCONFIGURED
          comment: set by automation
...

        PGPOOL_BACKEND_NODES: autoconfigured

...

      pool_hba_conf: autoconfigured

...
```
:white_check_mark: `epicli apply` with PostgreSQL vms and Pgpool deployment enabled
No problems encountered :heavy_check_mark:
