### ISSUE TITLE
[BUG] v0.6 Re-running single machine installation fails

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#1841]
**Describe the bug**
Re-running single machine installation fails with error:
`020-11-09T11:51:25.7815801Z 31;21m11:51:25 ERROR epicli - ControlPlane downscale is not supported yet. Please revert your kubernetes_master count to previous value or increase it to scale up kubernetes.
`

**To Reproduce**
1. execute `epicli apply -f testsingle.yml`
2. execute `epicli apply -f testsingle.yml`

**Expected behavior**
The cluster has been successfully deployed a second time.

**Config files**
```yaml
  components:
    kafka:
      count: 0
    kubernetes_master:
      count: 0
    kubernetes_node:
      count: 0
    load_balancer:
      count: 0
    logging:
      count: 0
    monitoring:
      count: 0
    postgresql:
      count: 0
    rabbitmq:
      count: 0
    ignite:
      count: 0
    opendistro_for_elasticsearch:
      count: 0
    single_machine:
      count: 1
```

**OS (please complete the following information):**
 - OS: [all]

**Cloud Environment (please complete the following information):**
 - Cloud Provider [all]

**Additional context**
The problem arises because the `kubernetes_master` group with one entry appears in the inventory file, and in the configuration yaml file we set the number of `kubernetes_master` to `0` and thus the assertion `if prev_master_count > next_master_count` throws an exception and stops the installation.
**There is a bugfix [#1216](https://github.com/epiphany-platform/epiphany/pull/1216) that needs to be backported to v0.6**.
