### ISSUE TITLE
[BUG] epicli upgrade of cluster created by Epiphany v0.6 fails on [preflight_facts : Store preflight facts] task

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#1887]
**Describe the bug**
Error message:
`PermissionError: [Errno 1] Operation not permitted: /shared/build/06hatodevawrhcalico/vault//../preflight_facts.yml`

Cause:
```
root@vm-bld-node-001:~# ls -la /tmp/build/epi-cli/build/06hatodevawrhcanal/
total 104
drwxr-xr-x  6 operations operations  4096 Dec  3 19:01 .
drwxr-xr-x 84 operations operations 12288 Dec  3 11:22 ..
drwxr-xr-x  5 operations operations  4096 Dec  3 19:01 ansible
drwxr-xr-x  5 operations operations  4096 Dec  3 19:01 backup_1606953697690
-rw-r--r--  1 operations operations  4481 Dec  3 19:01 inventory
-rw-r--r--  1 operations operations 60601 Dec  2 17:54 manifest.yml
-rw-r--r--  1 root       root         446 Dec  2 17:56 preflight_facts.yml
drwxr-xr-x  2 operations operations  4096 Dec  2 17:54 terraform
drwxr-xr-x  2 operations operations  4096 Dec  2 18:32 vault
```

PR #1825 added the `mode` parameter to the `Store preflight facts` task:

```
- name: Store preflight facts
  delegate_to: localhost
  become: false
  run_once: true
  copy:
    dest: "{{ vault_location }}/../preflight_facts.yml"
    mode: u=rw,g=r,o=
```

and the `become` parameter has been added in v0.7.

**How to reproduce**
1. Deploy cluster using epici v0.6
2. Run `epicli upgrade` using code from develop branch.

**Expected behavior**
`epicli upgrade` should succeed.

**Environment**
- Cloud provider: All
- OS: All

**Additional context**
n/a
