### ISSUE TITLE
[BUG] RabbitMQ installation fails on re-run with the stop_service parameter value changed from true to false

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#1923]
**Describe the bug**
There is an issue with RabbitMQ installation/configuration when running `epicli apply` for the second time with the `stop_service` parameter value changed from `true` to `false`.
More information on the use of the parameter can be found [here](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/SECURITY.md#how-to-use-tlsssl-certificate-with-rabbitmq).

**How to reproduce**
1. Deploy a cluster with RabbitMQ component enabled (2 vms) with the following config:
```yaml
---        
kind: configuration/rabbitmq
title: "RabbitMQ"
provider: aws
name: default
specification:
  stop_service: true
  rabbitmq_plugins:
    - rabbitmq_management_agent
    - rabbitmq_management
  cluster:
    is_clustered: true
```
2. Change the `stop_service` parameter value changed from `true` to `false`.
```yaml
---        
kind: configuration/rabbitmq
title: "RabbitMQ"
provider: aws
name: default
specification:
  stop_service: false
  rabbitmq_plugins:
    - rabbitmq_management_agent
    - rabbitmq_management
  cluster:
    is_clustered: true
```

**Expected behavior**
The RabbitMQ cluster has been deployed successfully.

**Actual behavior**
Installation fails on RabbitMQ installation.

**Environment**
- Cloud provider: [all]
- OS: [all]

**Additional context**
Logs:
```
2020-12-17T13:06:57.3366488Z [38;21m13:06:57 INFO cli.engine.ansible.AnsibleCommand - TASK [rabbitmq : Stop application] *********************************************[0m
2020-12-17T13:06:58.4926340Z [31;21m13:06:58 ERROR cli.engine.ansible.AnsibleCommand - fatal: [ec2-x-x-x-x.eu-west-3.compute.amazonaws.com]: FAILED! => {"changed": true, "cmd": ["rabbitmqctl", "stop_app"], "delta": "0:00:00.454892", "end": "2020-12-17 13:06:58.417482", "msg": "non-zero return code", "rc": 69, "start": "2020-12-17 13:06:57.962590", "stderr": "Error: unable to perform an operation on node 'rabbit@ec2-x-x-x-x'. Please see diagnostics information and suggestions below.\n\nMost common reasons for this are:\n\n * Target node is unreachable (e.g. due to hostname resolution, TCP connection or firewall issues)\n * CLI tool fails to authenticate with the server (e.g. due to CLI tool's Erlang cookie not matching that of the server)\n * Target node is not running\n\nIn addition to the diagnostics info below:\n\n * See the CLI, clustering and networking guides on https://rabbitmq.com/documentation.html to learn more\n * Consult server logs on node rabbit@ec2-x-x-x-x\n * If target node is configured to use long node names, don't forget to use --longnames with CLI tools\n\nDIAGNOSTICS\n===========\n\nattempted to contact: ['rabbit@ec2-x-x-x-x']\n\nrabbit@ec2-x-x-x-x:\n  * connected to epmd (port 4369) on ec2-x-x-x-x\n  * epmd reports: node 'rabbit' not running at all\n                  no other nodes on ec2-x-x-x-x\n  * suggestion: start the node\n\nCurrent node details:\n * node name: 'rabbitmqcli-7443-rabbit@ec2-x-x-x-x'\n * effective user's home directory: /var/lib/rabbitmq\n * Erlang cookie hash: VWMcyCnrwp7lv3ScwbL/qQ==", "stderr_lines": ["Error: unable to perform an operation on node 'rabbit@ec2-x-x-x-x'. Please see diagnostics information and suggestions below.", "", "Most common reasons for this are:", "", " * Target node is unreachable (e.g. due to hostname resolution, TCP connection or firewall issues)", " * CLI tool fails to authenticate with the server (e.g. due to CLI tool's Erlang cookie not matching that of the server)", " * Target node is not running", "", "In addition to the diagnostics info below:", "", " * See the CLI, clustering and networking guides on https://rabbitmq.com/documentation.html to learn more", " * Consult server logs on node rabbit@ec2-x-x-x-x", " * If target node is configured to use long node names, don't forget to use --longnames with CLI tools", "", "DIAGNOSTICS", "===========", "", "attempted to contact: ['rabbit@ec2-x-x-x-x']", "", "rabbit@ec2-x-x-x-x:", "  * connected to epmd (port 4369) on ec2-x-x-x-x", "  * epmd reports: node 'rabbit' not running at all", "                  no other nodes on ec2-x-x-x-x", "  * suggestion: start the node", "", "Current node details:", " * node name: 'rabbitmqcli-7443-rabbit@ec2-x-x-x-x'", " * effective user's home directory: /var/lib/rabbitmq", " * Erlang cookie hash: VWMcyCnrwp7lv3ScwbL/qQ=="], "stdout": "Stopping rabbit application on node rabbit@ec2-x-x-x-x ...", "stdout_lines": ["Stopping rabbit application on node rabbit@ec2-x-x-x-x ..."]}
```
It looks like it wants to stop an already stopped service, leading to installation failure.
