### ISSUE TITLE
[FEATURE REQUEST] Add arm64 support to 'repository' component

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#2033]
**Is your feature request related to a problem? Please describe.**
Currently we only support the x86_64 architectures but we need to add support for arm64.

**Describe the solution you'd like**
- We want the ability to install the ```repository``` component on an arm64 machine running CentOS. 
- The download-requirment.sh scripts (CentOS-7, Ubuntu-18.04, Redhat-7) will be modified to support requirement.txt inputs for x86_64 and arm64 as proposed [here](https://github.com/epiphany-platform/epiphany/blob/develop/docs/design-docs/arm/arm.md#repostitory-role).
- For CentOS a preliminary requirements_arm64.txt will be added based on the research [here](https://github.com/epiphany-platform/epiphany/blob/develop/docs/design-docs/arm/centos-arm-analysis.md). Ubuntu-18.04 and Redhat-7 are not of concern jet.
- The download role will be modified to allow download with arch modifications as proposed [here](https://github.com/epiphany-platform/epiphany/blob/develop/docs/design-docs/arm/arm.md#download-role) 

Effected Ansible roles:
- repository
- image-registry
- common
- downloads
- helm
- firewall

Skip the following Ansible roles for now by using a custom ```feature-mapping``` config:
- filebeat
- node-exporter

**Describe alternatives you've considered**
None.

**Additional context**
No.

**Extra info**
Design document and resources:
https://github.com/epiphany-platform/epiphany/tree/develop/docs/design-docs/arm

Terraform scripts for ARM hardware on AWS:
https://github.com/mkyc/aws-arm-simple-setup

YAML for testing:
```YAML
kind: epiphany-cluster
title: Epiphany cluster Config
provider: any
name: default
specification:
  name: test
  admin_user:
    name: operations
    key_path: /user/.ssh/epiphany-operations/id_rsa
  components:
    repository:
      count: 1
      machines:
      - default-repository
    kubernetes_master:
      count: 0
    kubernetes_node:
      count: 0
    logging:
      count: 0
    monitoring:
      count: 0
    kafka:
      count: 0
    postgresql:
      count: 0
    load_balancer:
      count: 0
    rabbitmq:
      count: 0
version: 0.11.0
---
kind: infrastructure/machine
provider: any
name: default-repository
specification:
  hostname: repository
  ip: ip #192.168.100.112
version: 0.11.0
---
kind: configuration/feature-mapping
title: "Feature mapping to roles"
name: default
provider: any
version: 0.11.0
specification:
  available_roles:
    - name: repository
      enabled: yes
    - name: firewall
      enabled: yes
    - name: image-registry
      enabled: yes
    - name: kubernetes-master
      enabled: yes
    - name: kubernetes-node
      enabled: yes
    - name: helm
      enabled: yes
    - name: logging
      enabled: yes
    - name: opendistro-for-elasticsearch
      enabled: yes
    - name: elasticsearch
      enabled: yes
    - name: elasticsearch-curator
      enabled: yes
    - name: kibana
      enabled: yes
    - name: filebeat
      enabled: yes
    - name: logstash
      enabled: yes
    - name: prometheus
      enabled: yes
    - name: grafana
      enabled: yes
    - name: node-exporter
      enabled: yes
    - name: jmx-exporter
      enabled: yes
    - name: zookeeper
      enabled: yes
    - name: kafka
      enabled: yes
    - name: rabbitmq
      enabled: yes
    - name: kafka-exporter
      enabled: yes
    - name: postgresql
      enabled: yes
    - name: postgres-exporter
      enabled: yes
    - name: haproxy
      enabled: yes
    - name: haproxy-exporter
      enabled: yes
    - name: vault
      enabled: yes
    - name: applications
      enabled: yes
    - name: ignite
      enabled: yes
  roles_mapping:
    kafka:
      - zookeeper
      - jmx-exporter
      - kafka
      - kafka-exporter
      - node-exporter
      - filebeat
      - firewall
    rabbitmq:
      - rabbitmq
      - node-exporter
      - filebeat
      - firewall
    logging:
      - logging
      - kibana
      - node-exporter
      - filebeat
      - firewall
    load_balancer:
      - haproxy
      - haproxy-exporter
      - node-exporter
      - filebeat
      - firewall
    monitoring:
      - prometheus
      - grafana
      - node-exporter
      - filebeat
      - firewall
    postgresql:
      - postgresql
      - postgres-exporter
      - node-exporter
      - filebeat
      - firewall
    custom:
      - repository
      - image-registry
      - kubernetes-master
      - node-exporter
      - filebeat
      - rabbitmq
      - postgresql
      - prometheus
      - grafana
      - node-exporter
      - logging
      - firewall
    single_machine:
      - repository
      - image-registry
      - kubernetes-master
      - helm
      - applications
      - rabbitmq
      - postgresql
      - firewall
      - vault
    kubernetes_master:
      - kubernetes-master
      - helm
      - applications
      - node-exporter
      - filebeat
      - firewall
      - vault
    kubernetes_node:
      - kubernetes-node
      - node-exporter
      - filebeat
      - firewall
    ignite:
      - ignite
      - node-exporter
      - filebeat
      - firewall
    opendistro_for_elasticsearch:
      - opendistro-for-elasticsearch
      - node-exporter
      - filebeat
      - firewall
    repository:
      - repository
      - image-registry
      - firewall
      #- filebeat
      #- node-exporter
```

---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license
