### ISSUE TITLE
[BUG] The default values can't be changed in cluster config file for virtual machine.

### ISSUE THREAD

**Issue by rpudlowski93** [epiphany-platform/epiphany#2098]
**Describe the bug**
It is not possible to change default values in configuration section for infrastructure/virtual-machine such as: 
- disk_size_gb
- offer
- sku 
etc... in cluster config file. Terraform use always default ones. 

**How to reproduce**
1. execute `epicli init ... (with params)`
2. edit config file and change default os_disk_size or os image
3. execute `epicli apply ...`

**Expected behavior**
I would like to create cluster with the values which I set in my configuration file. 
If I set 64GB os disk size, I would like to have 64GB os disk size, not the default 32GB

**Config files**
```
---
kind: infrastructure/virtual-machine
title: Virtual Machine Infra
provider: azure
name: default
specification:
  tags: []
  os_type: linux
  size: Standard_DS1_v2
  storage_image_reference:
    publisher: Canonical
    offer: UbuntuServer
    sku: 18_04-lts-gen2
    version: 18.04.202101290
  storage_os_disk:
    delete_on_termination: false
    managed: false
    caching: ReadWrite
    create_option: FromImage
    disk_size_gb: 64
    managed_disk_type: Premium_LRS
```
**Environment**
- Cloud provider: [AWS | Azure]
- OS: [all]

**epicli version**: 0.9

**Additional context**

---

**DoD checklist**

* [x] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Case covered by automated test (if possible)
* [ ] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved

**Comment by przemyslavic** [comment]
@rpudlowski93 
For now, the only option to change these parameters is to provide the configuration for each vm like this:
```yaml
---
kind: epiphany-cluster
name: default
provider: azure
specification:
  admin_user:
    key_path: /path/to/id_rsa
    name: operations
  cloud:
    region: West Europe
    subscription_name: xxx
    use_public_ips: false
    use_service_principal: true   
  components:
    kafka:
      count: 2
      machine: kafka-machine-rhel
    kubernetes_master:
      count: 1
      machine: kubernetes-master-machine-rhel
    kubernetes_node:
      count: 2
      machine: kubernetes-node-machine-rhel
    load_balancer:
      count: 1
      machine: lb-machine-rhel  
    logging:
      count: 2
      machine: logging-machine-rhel
    monitoring:
      count: 1
      machine: monitoring-machine-rhel
    postgresql:
      count: 2
      machine: postgresql-machine-rhel
    rabbitmq:
      count: 2
      machine: rabbitmq-machine-rhel
    ignite:
      count: 2
      machine: ignite-machine-rhel
    opendistro_for_elasticsearch:
      count: 2
      machine:  opendistro-machine-rhel
    repository:
      count: 1
      machine:  repository-machine-rhel
  name: test
  prefix: 'qa'
title: Epiphany cluster Config
---
kind: infrastructure/virtual-machine
name: kafka-machine-rhel
provider: azure
based_on: kafka-machine
specification:
  storage_image_reference:
    publisher: RedHat
    offer: RHEL
    sku: 7-LVM
    version: "7.9.2020111202"
  storage_os_disk:
    disk_size_gb: 64
---
kind: infrastructure/virtual-machine
name: kubernetes-master-machine-rhel
provider: azure
based_on: kubernetes-master-machine
specification:
  storage_image_reference:
    publisher: RedHat
    offer: RHEL
    sku: 7-LVM
    version: "7.9.2020111202"
  storage_os_disk:
    disk_size_gb: 64
---
kind: infrastructure/virtual-machine
name: kubernetes-node-machine-rhel
provider: azure
based_on: kubernetes-node-machine
specification:
  storage_image_reference:
    publisher: RedHat
    offer: RHEL
    sku: 7-LVM
    version: "7.9.2020111202"
  storage_os_disk:
    disk_size_gb: 64
---
kind: infrastructure/virtual-machine
name: logging-machine-rhel
provider: azure
based_on: logging-machine
specification:
  storage_image_reference:
    publisher: RedHat
    offer: RHEL
    sku: 7-LVM
    version: "7.9.2020111202"
  storage_os_disk:
    disk_size_gb: 64
---
kind: infrastructure/virtual-machine
name: monitoring-machine-rhel
provider: azure
based_on: monitoring-machine
specification:
  storage_image_reference:
    publisher: RedHat
    offer: RHEL
    sku: 7-LVM
    version: "7.9.2020111202"
  storage_os_disk:
    disk_size_gb: 64
---
kind: infrastructure/virtual-machine
name: postgresql-machine-rhel
provider: azure
based_on: postgresql-machine
specification:
  storage_image_reference:
    publisher: RedHat
    offer: RHEL
    sku: 7-LVM
    version: "7.9.2020111202"
  storage_os_disk:
    disk_size_gb: 64
---
kind: infrastructure/virtual-machine
name: lb-machine-rhel
provider: azure
based_on: load-balancer-machine
specification:
  storage_image_reference:
    publisher: RedHat
    offer: RHEL
    sku: 7-LVM
    version: "7.9.2020111202"
  storage_os_disk:
    disk_size_gb: 64
---
kind: infrastructure/virtual-machine
name: rabbitmq-machine-rhel
provider: azure
based_on: rabbitmq-machine
specification:
  storage_image_reference:
    publisher: RedHat
    offer: RHEL
    sku: 7-LVM
    version: "7.9.2020111202"
  storage_os_disk:
    disk_size_gb: 64
---
kind: infrastructure/virtual-machine
name: ignite-machine-rhel
provider: azure
based_on: ignite-machine
specification:
  storage_image_reference:
    publisher: RedHat
    offer: RHEL
    sku: 7-LVM
    version: "7.9.2020111202"
  storage_os_disk:
    disk_size_gb: 64
---
kind: infrastructure/virtual-machine
name: opendistro-machine-rhel
provider: azure
based_on: logging-machine
specification:
  storage_image_reference:
    publisher: RedHat
    offer: RHEL
    sku: 7-LVM
    version: "7.9.2020111202"
  storage_os_disk:
    disk_size_gb: 64
---
kind: infrastructure/virtual-machine
name: repository-machine-rhel
provider: azure
based_on: repository-machine
specification:
  storage_image_reference:
    publisher: RedHat
    offer: RHEL
    sku: 7-LVM
    version: "7.9.2020111202"
  storage_os_disk:
    disk_size_gb: 64
```

**Comment by atsikham** [comment]
This is a bug as specifying "default" virtual-machine type should affect/override parameters of other virtual machine types that are not specified explicitly. Doing this way it should be possible to specify common parameters in the single place.

@seriva will check and post here the configuration that was working in previous versions.

Important notes:
1. There is [based_on](https://github.com/epiphany-platform/epiphany/blob/585e9ce284bef93a0512dad3440ef39162405efc/core/src/epicli/cli/engine/schema/DefaultMerger.py#L25) option that allows any configuration inherriting ancestor's parameters.
2. Related documentation have to be updated.

**Comment by seriva** [comment]
I tested the following config from 0.6.x and up to 0.9.x and it seems to be broken everywhere (or never worked;)):

```yaml
kind: epiphany-cluster
name: default
provider: azure
title: Epiphany cluster Config
specification:
  prefix: test
  name: test
  admin_user:
    name: operations
    key_path: /home/epiuser/ssh/id_rsa
  cloud:
    region: East US
    subscription_name: xxx
    use_public_ips: false
    use_service_principal: true
  components:
    kubernetes_master:
      count: 1
    kubernetes_node:
      count: 6
    kafka:
      count: 3
    postgresql:
      count: 1
    monitoring:
      count: 1
    logging:
      count: 1
    rabbitmq:
      count: 0
    load_balancer:
      count: 0
---
kind: infrastructure/virtual-machine
title: "Virtual Machine Infra"
provider: azure
name: default
specification:
  storage_os_disk:
    disk_size_gb: 128
---
kind: infrastructure/virtual-machine
title: Virtual Machine Infra
provider: azure
name: kubernetes-master-machine
specification:
  size: Standard_D4s_v3
  storage_os_disk:
    disk_size_gb: 256
```

Like @atsikham mentioned: This should make every disk 128gb, except for the K8s master machine which should be 256gb

**Comment by przemyslavic** [comment]
Unfortunately the fix is not working properly. For the configuration below, OS for only one vm is changed.
```yaml
---
kind: epiphany-cluster
name: default
provider: aws
specification:
  admin_user:
    key_path: /path/to/id_rsa
    name: ec2-user
  cloud:
    credentials:
      key: 
      secret: 
    region: eu-west-2
    use_public_ips: true
  components:
    kafka:
      count: 1
    kubernetes_master:
      count: 1
    kubernetes_node:
      count: 1
    load_balancer:
      count: 1
    logging:
      count: 1
    monitoring:
      count: 1
    postgresql:
      count: 1
    rabbitmq:
      count: 1
    ignite:
      count: 1
    opendistro_for_elasticsearch:
      count: 1
    repository:
      count: 1
  name: defaultsfix
  prefix: 'qa'
title: Epiphany cluster Config
---
kind: infrastructure/virtual-machine
title: "Virtual Machine Infra"
provider: aws
name: default
specification:
  os_full_name: RHEL-7.9_HVM-20210208-x86_64-0-Hourly2-GP2
```
```
13:27:23 INFO cli.engine.schema.SchemaValidator - Run done in 116ms
13:27:23 ERROR epicli - Detected mixed Linux distros in config, Epirepo will not work properly. Please inspect your config manifest. Forgot to define repository VM document?
```

Same for disk size:
```yaml
---
kind: infrastructure/virtual-machine
title: "Virtual Machine Infra"
provider: aws
name: default
specification:
  disks:
    root:
      volume_size: 128
```
Only one vm has a 128GB disk.
Moving back to TODO.
