### ISSUE TITLE
[FEATURE REQUEST] Add arm64 support to 'kubernetes_master' and 'kubernetes_node' components

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2109]
**Is your feature request related to a problem? Please describe.**
Currently we only support the x86_64 architectures but we need to add support for arm64.

**Describe the solution you'd like**
- We want the ability to install the ```kubernetes_master``` and  ```kubernetes_node``` components on arm64 machines running CentOS. 
- We want to focus on the single master with 1..n nodes scenario.
- Only the latest version we support: 1.18.6
- Any requirements missing or not added in #2033 will be added for the effected roles.
- vault, exporters, filebeat can be skipped at this point.

Effected Ansible roles:
- kubernetes-master
- kubernetes-node
- kubernetes-common
- kubernetes_promote? ('should' not be needed as promoting single master to multi master)
- helm
- docker
- common
- haproxy_runc? ('should' not be needed as thats only for multi master)
- firewall

Skip the following Ansible roles for now by using a custom ```feature-mapping``` config:
- applications
- node-exporter
- filebeat
- vault

**Describe alternatives you've considered**
None.

**Additional context**
No.

**Extra info**
Design document and resources:
https://github.com/epiphany-platform/epiphany/tree/develop/docs/design-docs/arm

Terraform scripts for ARM hardware on AWS:
https://github.com/mkyc/aws-arm-simple-setup

YAML for testing:
```YAML
kind: epiphany-cluster
title: Epiphany cluster Config
provider: any
name: default
specification:
  name: test
  admin_user:
    name: operations
    key_path: /user/.ssh/epiphany-operations/id_rsa
  components:
    repository:
      count: 1
      machines:
      - default-repository
    kubernetes_master:
      count: 1
      machines:
      - default-k8s-master1
    kubernetes_node:
      count: 2
      machines:
      - default-k8s-node1
      - default-k8s-node2
    logging:
      count: 0
    monitoring:
      count: 0
    kafka:
      count: 0
    postgresql:
      count: 0
    load_balancer:
      count: 0
    rabbitmq:
      count: 0
version: 0.11.0
---
kind: infrastructure/machine
provider: any
name: default-repository
specification:
  hostname: repository
  ip: ip #192.168.100.112
version: 0.11.0
---
kind: infrastructure/machine
provider: any
name: default-k8s-master1
specification:
  hostname: master1
  ip: ip #192.168.100.101
version: 0.11.0
---
kind: infrastructure/machine
provider: any
name: default-k8s-node1
specification:
  hostname: node1
  ip: ip #192.168.100.102
version: 0.11.0
---
kind: infrastructure/machine
provider: any
name: default-k8s-node2
specification:
  hostname: node2
  ip: ip #192.168.100.103
version: 0.11.0
---
kind: configuration/feature-mapping
title: "Feature mapping to roles"
name: default
provider: any
version: 0.11.0
specification:
  available_roles:
    - name: repository
      enabled: yes
    - name: firewall
      enabled: yes
    - name: image-registry
      enabled: yes
    - name: kubernetes-master
      enabled: yes
    - name: kubernetes-node
      enabled: yes
    - name: helm
      enabled: yes
    - name: logging
      enabled: yes
    - name: opendistro-for-elasticsearch
      enabled: yes
    - name: elasticsearch
      enabled: yes
    - name: elasticsearch-curator
      enabled: yes
    - name: kibana
      enabled: yes
    - name: filebeat
      enabled: yes
    - name: logstash
      enabled: yes
    - name: prometheus
      enabled: yes
    - name: grafana
      enabled: yes
    - name: node-exporter
      enabled: yes
    - name: jmx-exporter
      enabled: yes
    - name: zookeeper
      enabled: yes
    - name: kafka
      enabled: yes
    - name: rabbitmq
      enabled: yes
    - name: kafka-exporter
      enabled: yes
    - name: postgresql
      enabled: yes
    - name: postgres-exporter
      enabled: yes
    - name: haproxy
      enabled: yes
    - name: haproxy-exporter
      enabled: yes
    - name: vault
      enabled: yes
    - name: applications
      enabled: yes
    - name: ignite
      enabled: yes
  roles_mapping:
    kafka:
      - zookeeper
      - jmx-exporter
      - kafka
      - kafka-exporter
      - node-exporter
      - filebeat
      - firewall
    rabbitmq:
      - rabbitmq
      - node-exporter
      - filebeat
      - firewall
    logging:
      - logging
      - kibana
      - node-exporter
      - filebeat
      - firewall
    load_balancer:
      - haproxy
      - haproxy-exporter
      - node-exporter
      - filebeat
      - firewall
    monitoring:
      - prometheus
      - grafana
      - node-exporter
      - filebeat
      - firewall
    postgresql:
      - postgresql
      - postgres-exporter
      - node-exporter
      - filebeat
      - firewall
    custom:
      - repository
      - image-registry
      - kubernetes-master
      - node-exporter
      - filebeat
      - rabbitmq
      - postgresql
      - prometheus
      - grafana
      - node-exporter
      - logging
      - firewall
    single_machine:
      - repository
      - image-registry
      - kubernetes-master
      - helm
      - applications
      - rabbitmq
      - postgresql
      - firewall
      - vault
    kubernetes_master:
      - kubernetes-master
      - helm
      #- applications
      #- node-exporter
      #- filebeat
      - firewall
      #- vault
    kubernetes_node:
      - kubernetes-node
      #- node-exporter
      #- filebeat
      #- firewall
    ignite:
      - ignite
      - node-exporter
      - filebeat
      - firewall
    opendistro_for_elasticsearch:
      - opendistro-for-elasticsearch
      - node-exporter
      - filebeat
      - firewall
    repository:
      - repository
      - image-registry
      - firewall
      #- filebeat
      #- node-exporter
```

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
