### ISSUE TITLE
[BUG] Previously installed Prometheus fails on reapplying configuration from develop.

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#2154]
**Describe the bug**
Previously installed Prometheus with epicli < develop (0.10) fails when reapplying configuration from develop branch. It fails on task `Create Prometheus system user` with error `usermod: user prometheus is currently used by process 10724`.

This is probably due to a recent change in Prometheus installation task:
https://github.com/epiphany-platform/epiphany/commit/3c56ac06f0c1eae3d287f60ae8c3f4dfa3cc59e0#diff-514b59b4163f0409936ccdd7a2779e95a2d56193462d887a5535441edee867adR15

**How to reproduce**
1. execute `epicli apply` from v0.8 branch (or v0.9)
2. ~~execute `epicli upgrade` from develop branch - this can be skipped but it reflects a real use case~~
3. execute `epicli apply` from develop branch

**Expected behavior**
No issues during installation.

**Config files**
```yaml
specification:
  components:
    kafka:
      count: 0
    kubernetes_master:
      count: 0
    kubernetes_node:
      count: 0
    load_balancer:
      count: 0
    logging:
      count: 0
    monitoring:
      count: 1
    postgresql:
      count: 0
    rabbitmq:
      count: 0
    ignite:
      count: 0
    opendistro_for_elasticsearch:
      count: 0
    repository:
      count: 1
```

**Environment**
- Cloud provider: [all]
- OS: [all]

**epicli version**: [`epicli --version`]
develop

**Additional context**
```
2021-03-25T11:52:19.1148978Z [38;21m11:52:19 INFO cli.engine.ansible.AnsibleCommand - TASK [prometheus : Create Prometheus system user] ******************************[0m
2021-03-25T11:52:20.2324300Z [31;21m11:52:20 ERROR cli.engine.ansible.AnsibleCommand - fatal: [ec2-xx-xx-xx-xx.eu-west-1.compute.amazonaws.com]: FAILED! => {"changed": false, "msg": "usermod: user prometheus is currently used by process 10724\n", "name": "prometheus", "rc": 8}
```

---

**DoD checklist**

* [x] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [x] Case covered by automated test (if possible)
* [x] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved
