### ISSUE TITLE
[BACKPORT][1.0.1] Allow to preserve OS images when run 'epicli apply' for existing cluster

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2336]
Backport issues #2288
Related pull requests: #2329

**Comment by przemyslavic** [comment]
Tested together with #2333.

Tested:
✅ `apply` v0.9 -> `upgrade` to v1.0 -> `apply` v1.0
✅  `apply` v1.0-> `apply` v1.0

I checked different values for `default_os_image` parameter:
- `ubuntu-18.04-x86_64`

- `redhat-7-x86_64`

- `centos-7-x86_64`

- `centos-7-arm64` (only terraform part as arm support will be introduced in v1.1.0)

- `default`

also with changed default specification:
```yaml
---
kind: infrastructure/virtual-machine
title: "Virtual Machine Infra"
provider: aws
name: default
specification:
  os_full_name: RHEL-7.9_HVM-20210208-x86_64-0-Hourly2-GP2
```
both for `Azure` and `AWS`.
