### ISSUE TITLE
[BUG] Decreasing the amount of Epiphany components is causing the Terraform error

### ISSUE THREAD

**Issue by romsok24** [epiphany-platform/epiphany#2354]
**Describe the bug**
Decreasing the amount of Epiphany components is causing the Terraform error.
Error details: 
```
Error creating route table association: Resource.AlreadyAssociated: the specified association for route table rtb-xxxxxxxxxx conflicts with an existing association
nd -   status code: 400
on build/qstart/terraform/009_ros-qstart-kubernetes-master-0-route-association.tf line 14, in resource "aws_route_table_association" "ros-qstart-kubernetes-master-0-route-association":
 resource "aws_route_table_association" "ros-qstart-kubernetes-master-0-route-association" 
ERROR epicli - Error running: "terraform apply --auto-approve -state=/shared/build/qstart/terraform//terraform.tfstate -no-color /shared/build/qstart/terraform/"
```

**How to reproduce**
( on the correctly deployed minimum Epiphany environment )
1. edit configuration file `/shared/build/qstart/qstart.yml`  by changing:
   ```
    kafka:
      count: 1
   ```
   to 
   ```
    kafka:
      count: 0
   ```
2. execute `epicli apply  -f /shared/build/qstart/qstart.yml`

**Expected behavior**
The Epiphany environment should be successfully downgraded in order to not include the `kafka` component.

**Config files**
```
kind: epiphany-cluster
title: Epiphany cluster Config
provider: aws
name: default
specification:
  name: qstart
  prefix: ros
  admin_user:
    name: operations
    key_path: /shared/.ssh/id_rsa
  cloud:
    k8s_as_cloud_service: false
    use_public_ips: false
    credentials:
      key: xxxxxxxxxxxxxxxxxxxxxxxxxxx
      secret: yyyyyyyyyyyyyyyyyyyyyyyyyyyyy
  components:
    repository:
      count: 1
    kubernetes_master:
      count: 1
    kubernetes_node:
      count: 1
    logging:
      count: 1
    monitoring:
      count: 1
    kafka:
      count: 0
    postgresql:
      count: 1
    load_balancer:
      count: 1
    rabbitmq:
      count: 1
version: 1.0.0
```

**Environment**
- Cloud provider: AWS
- OS:  Debian 10 ( _epicli container_ )

**epicli version**: 1.0.0

---

**DoD checklist**

* [ ] Changelog updated (if affected version was released)
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Case covered by automated test (if possible)
* [ ] Idempotency tested
* [ ] Documentation updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Backport tasks created / doesn't need to be backported
