### ISSUE TITLE
[BACKPORT][0.9.3] Allow to specify configuration to be used in upgrade mode

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2390]
Source issue #2127
Pull request #2384

---

**DoD checklist**

* [x] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
Tested the following scenario:
- `epicli apply` v0.8.3

- `cat /shared/build/upgradetest/ansible/roles/logging/vars/main.yml`
```
kind: configuration/logging
title: Logging Config
name: default
specification:
  cluster_name: EpiphanyElastic
  clustered: true
  paths:
    data: /var/lib/elasticsearch
    repo: /var/lib/elasticsearch-snapshots
    logs: /var/log/elasticsearch
  jvm_options:
    Xmx: 1g
  provider: aws
version: 0.8.3
```
- `cat /shared/build/upgradetest/ansible/roles/rabbitmq/vars/main.yml`
```
kind: configuration/rabbitmq
title: RabbitMQ
name: default
specification:
  rabbitmq_user: rabbitmq
  rabbitmq_group: rabbitmq
  stop_service: false
  logrotate_period: weekly
  logrotate_number: 10
  ulimit_open_files: 65535
  amqp_port: 5672
  rabbitmq_use_longname: AUTOCONFIGURED
  rabbitmq_policies: []
  rabbitmq_plugins: []
  custom_configurations: []
  cluster:
    is_clustered: false
  provider: aws
version: 0.8.3
```
- create configuration file for upgrade
```
---
kind: configuration/rabbitmq
title: "RabbitMQ"
provider: aws
name: default
specification:
  logrotate_period: daily
  logrotate_number: 9
  ulimit_open_files: 256
  rabbitmq_plugins:
    - rabbitmq_management_agent
    - rabbitmq_management
  cluster:
    is_clustered: false
---
kind: configuration/logging
title: Logging Config
name: default
provider: aws
specification:
  cluster_name: NameAferUpgrade
  jvm_options:
    Xmx: 2g
```
- execute `epicli upgrade` with `-f /shared/build/upgradetest/upgradeconfig.yml` parameter

- `cat /shared/build/upgradetest/ansible/roles/logging/vars/main.yml`
```
kind: configuration/logging
title: Logging Config
name: default
specification:
  cluster_name: NameAferUpgrade
  clustered: true
  paths:
    data: /var/lib/elasticsearch
    repo: /var/lib/elasticsearch-snapshots
    logs: /var/log/elasticsearch
  jvm_options:
    Xmx: 2g
  provider: aws
provider: aws
version: 0.9.2
```
- `cat /shared/build/upgradetest/ansible/roles/rabbitmq/vars/main.yml`
```
kind: configuration/rabbitmq
title: RabbitMQ
name: default
specification:
  rabbitmq_user: rabbitmq
  rabbitmq_group: rabbitmq
  stop_service: false
  logrotate_period: daily
  logrotate_number: 9
  ulimit_open_files: 256
  amqp_port: 5672
  rabbitmq_use_longname: AUTOCONFIGURED
  rabbitmq_policies: []
  rabbitmq_plugins:
  - rabbitmq_management_agent
  - rabbitmq_management
  custom_configurations: []
  cluster:
    is_clustered: false
  provider: aws
provider: aws
version: 0.9.2
```

:heavy_check_mark: It works as expected. Now there is a possibility to provide additional config for upgrading components.
