### ISSUE TITLE
[FEATURE REQUEST] Configure Elasticsearch Curator to work with Open Distro for Elasticsearch

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#2423]
**Is your feature request related to a problem? Please describe.**
After moving to Opendistro for Elasticsearch, Elasticsearch curator stopped working since there is a different way of authentication, but it's possible to use ILM plugin which supports limited set functionalities from Elasticsearch Curator.

**Describe the solution you'd like**
We want to perform configuration using http basic security and configure authentication of Elasticsearch Curator. We should also additional to this create proper role for Curator in Open Distro and limit possible permissions.

**Describe alternatives you've considered**
We can also use certificate authentication with Open Distro, but this will be more complicated.

**Additional context**
Possibility of performing this task was briefly checked in task #2149.

More you can find under links below:
https://www.elastic.co/guide/en/elasticsearch/client/curator/current/configfile.html#username
https://discuss.opendistrocommunity.dev/t/curator-set-up-with-keys-and-certificates/1368

---

**DoD checklist**

* [ ] Changelog updated
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Solution meets requirements and is done according to design doc
* [ ] Usage compliant with license
* [ ] Backport tasks created / doesn't need to be backported

**Comment by rafzei** [comment]
@to-bar @mkyc 
After some discussion with the internal team, it turned out that they are already using ISM for ODFE and Curator is only required to manage policies via cli tool. I've pointed them that ISM has an API for this purpose and it's easy to implement in ci/cd (They didn't know about the API).

IMO we can close this issue and create new one to implement some default policies using that API. 
We already have policies description in our docs:
https://github.com/plirglo/epiphany/blob/develop/docs/home/howto/LOGGING.md#how-to-manage-opendistro-for-elasticsearch-data
ISM API: https://opendistro.github.io/for-elasticsearch-docs/docs/im/ism/api/
Edit:
What I see ISM is also available in OpenSearch: https://opensearch.org/docs/im-plugin/ism/index/

**Comment by to-bar** [comment]
@rafzei IMO we should:
1) Spike ISM against a real Filebeat use case, which was covered by Curator in the past as follows:
```
delete_indices_cron_jobs:
  - description: Delete indices older than N days
    cron:
      hour: 1
      minute: 0
      enabled: true
    filter_list:
      - filtertype: age
        unit_count: 30
        unit: days
        source: creation_date
        direction: older
  - description: Delete the oldest indices to not consume more than N gigabytes of disk space
    cron:
      minute: 30
      enabled: true
    filter_list:
      - filtertype: space
        disk_space: 20
        use_age: True
        source: creation_date
```
2) If ISM is able to handle the use case, then we can close this task and implement ISM instead of Curator. Otherwise, this task is still valid.
