### ISSUE TITLE
[BUG] Feature-mapping - 'enabled: no' do nothing

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#2425]
**Describe the bug**
In feature-mapping setting flag `enabled: no` doesn't take effect.  

**How to reproduce**
- Increase `count` for some random components eg.:
```
kind: epiphany-cluster
title: Epiphany cluster Config
provider: azure
name: default
specification:
  components:
    monitoring:
      count: 1
    kafka:
      count: 1
```
- Add feature-mapping section to your initial configuration manifest with set `enabled: no` :
```
---
kind: configuration/feature-mapping
title: Feature mapping to roles
name: default
provider: azure
specification:
  available_roles:
  - name: kafka
    enabled: no
   - name: prometheus
    enabled: no
  - name: grafana
    enabled: no
  ...
```

**Expected behavior**
Disabled roles should be skipped.

**Environment**
- Cloud provider: [ All ] (tested on Azure)

**epicli version**: 1.2.0dev

---

**DoD checklist**

* [x] Changelog updated (if affected version was released)
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [ ] Case covered by automated test (if possible)
* [ ] Idempotency tested
* [ ] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Backport tasks created / doesn't need to be backported
