### ISSUE TITLE
[UPGRADE] Upgrade of PgBouncer [standalone]

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#2453]
Is your feature request related to a problem? Please describe.
We need to upgrade PgBouncer if possible and needed to the newer version. This task should be done after we will upgrade PostgreSQL to v13.
This task applies to standalone application

Describe the solution you'd like
We want to upgrade if possible and needed to the newer version of PgBouncer.

Describe alternatives you've considered
None.

Additional context
This task should be done after upgrade of PostgreSQL to v13.

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [x] upgrade
* [ ] Idempotency tested
* [x] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [ ] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment]
@atsikham @to-bar @plirglo 
1. Why do we install pgbouncer on all postgresql nodes and configure it only on one (first)?.
2. After re-runnig `epicli apply` command the order of the nodes may change, which will result in having pgbouncer configured on the master node (from the first run) and then configured on the second node pointing to a replica (on the second run), which may cause issues when running quries in a read-only transaction.
```
- name: Extensions | configure PgBouncer
  when: groups.postgresql[0] == inventory_hostname
```
3. Also during the upgrade, we start the pgbouncer service on both nodes, even if one of them has not been properly configured before.

```
    - name: PostgreSQL | Extensions | PgBouncer | Upgrade
      when: pg_is_pgbouncer_used
      block:
        - include_tasks: roles/postgresql/tasks/upgrade/extensions/pgbouncer/packages.yml

        - name: Extensions | PgBouncer | Ensure that systemd service is started
          systemd:
            name: pgbouncer
            state: started
```

I know that from the next version we will not support such an installation of pgbouncer, so if there is no point in fixing it, please just comment here.
