### ISSUE TITLE
Refactor upgrade role to not include "specification" at top level

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2485]
**Describe the bug**
In `upgrade` role there are `include_vars` tasks used without the `name` parameter what loads variables at top level with [higher precedence than task vars](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#understanding-variable-precedence).

So having in upgrade role:

```
- name: Node Exporter | Include specification vars from node_exporter role
  include_vars:
    file: roles/node_exporter/vars/main.yml
```

causes that `specification` of `node_exporter` is global with high precedence.
 
Then the following task (`postgresql` upgrade is run after `node_exporter`) has unexpected content (from `node_exporter`) in `specification` var:

```
- name: repmgr for PG {{ pg_version }} | Replace repmgr config file
  template:
    src: repmgr.conf.j2
    dest: "{{ upgrade_defaults.repmgr.config_dir[ansible_os_family] }}/repmgr.conf"
    owner: postgres
    group: postgres
    mode: u=rw,g=,o=
  vars:
    specification:
      extensions:
        replication:
          replication_user_name: "{{ postgresql_manifest.specification.extensions.replication.replication_user_name }}"
          repmgr_database:       "{{ postgresql_manifest.specification.extensions.replication.repmgr_database }}"
```

**Expected behavior**
Task `include_vars` should be used with `name` parameter, for example:

```
- name: Node Exporter | Include specification vars from node_exporter role
  include_vars:
    file: roles/node_exporter/vars/main.yml
    name: node_exporter_vars
```

then `specification` would not override task vars but be available under `node_exporter_vars.specification`.

**Additional context**
Having globally loaded vars with high precedence *may cause difficult to debug errors*.

For local vars we can use underscore in names, e.g. `_specification`.

---

**DoD checklist**

* [x] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [x] upgrade
* [ ] Case covered by automated test (if possible)
* [ ] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Backport tasks created / doesn't need to be backported
