### ISSUE TITLE
[FEATURE REQUEST] Add PyLint to build pipeline

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2535]
**Is your feature request related to a problem? Please describe.**
Currently we have the ability to use PyLint in the devcontainer and output the results in junit format.

**Describe the solution you'd like**
We want to integrate this into the Azure build pipelines as well and publish the results:

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=trx%2Cyaml

**Describe alternatives you've considered**
None

**Additional context**
See https://github.com/epiphany-platform/epiphany/blob/develop/core/src/epicli/.vscode/tasks.json how PyLint can be executed.

**Comment by mkyc** [comment]
Consider if we want to use GitHub Actions.

**Comment by przemyslavic** [comment]
To run PyLint in the pipeline:
- install `pylint` and `pylint_junit` plugin on the agent
- execute:
```
cd $(System.DefaultWorkingDirectory)
# pylint --rcfile .pylintrc ./cli ./tests --output-format colorized --exit-zero
mkdir -p test_results && pylint --rcfile .pylintrc ./cli ./tests --output test_results/pylint_results.xml --exit-zero
```
Don't forget about `--exit-zero` flag for CI scripts (https://github.com/PyCQA/pylint/blob/1.9/ChangeLog#L59)
- Publish results to Azure DevOps

GitHub action can be used as well.
```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run PyLint
        run: |
          pip install pylint pylint_junit
          mkdir -p test_results && pylint --rcfile .pylintrc ./cli ./tests --output test_results/pylint_results.xml --exit-zero

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: 'test_results/pylint_results.xml'
```

![image](https://user-images.githubusercontent.com/43173646/140765055-ec952f19-3bcd-444d-948e-5fb60ac029f9.png)
