### ISSUE TITLE
[PoC] check how to exact previous version of role for upgrade tests

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/epiphany#2694]
in molecule upgrade tests, we need to:
 - check if that is possible to use some role in specific version as dependency
 - asses if that makes any sense to release "role docker image" per version to use it later in upgrade testing

**Comment by atsikham** [comment]
Till this moment I was able to do that only in one way:

1. Create `collections-upgrade.yml` file that contains requirements to install previous collection version:

```yaml
collections:
  # Stub for upgrade, should contain source PostgreSQL version to upgrade from
  - name: https://github.com/epiphany-poc/postgresql.git
    type: git
    version: postgres-10
```

2. Use [shell](https://molecule.readthedocs.io/en/latest/configuration.html#shell) dependency manager:

```yaml
dependency:
  name: shell
  command: ${MOLECULE_PROJECT_DIRECTORY}/requirements.sh
  env:
    ANSIBLE_COLLECTIONS_PATH: ${MOLECULE_EPHEMERAL_DIRECTORY}/collections # specified here to avoid warning
```

`requirements.sh`:

```shell
#!/bin/bash

set -e

COLLECTION_REQUIREMENTS="${MOLECULE_PROJECT_DIRECTORY}/collections-upgrade.yml"
COLLECTION_REQUIREMENTS_FILE="${MOLECULE_EPHEMERAL_DIRECTORY}/collection-requirements.tmp"

if [[ -f "$COLLECTION_REQUIREMENTS_FILE" ]]; then
    COLLECTION_REQUIREMENTS=$(cat "$COLLECTION_REQUIREMENTS_FILE")
fi

echo "COLLECTION_REQUIREMENTS: ${COLLECTION_REQUIREMENTS}"

ansible-galaxy collection install --force -r "$COLLECTION_REQUIREMENTS" -p "$ANSIBLE_COLLECTIONS_PATH"
```

It uses `collections-upgrade.yml` by default and `collections.yml` that contains a reference to collection in the current version if there is a temporary file. This file is created in `prepare` playbook and removed in `cleanup`.

`prepare.yml`:

```yaml
---
- name: Prepare
  hosts: postgresql
  become: true
  become_method: sudo
  gather_facts: true
  module_defaults:
    shell:
      executable: /bin/bash
  tasks:
    - name: Include postgresql defaults
      include_vars:
        file: ../vars/config-old.yml
        name: apply_defaults

    - name: Override default configuration
      set_fact:
        config: "{{ apply_defaults.config }}"

    - name: Include postgresql apply role
      include_role:
        name: epi.postgresql.postgresql_apply
      vars:
        yum_lock_timeout: 300 # https://github.com/ansible/ansible/issues/57189
        roles_with_generated_vars: [ ] # don't execute PgPool related tasks

    - name: Create collection-requirements.tmp file
      copy:
        dest: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/collection-requirements.tmp"
        content: "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/collections.yml"
        force: true
      delegate_to: localhost
      run_once: true
```

`cleanup.yml`:

```yaml
---
- name: Cleanup
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove collection-requirements.tmp file
      ansible.builtin.file:
        path: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/collection-requirements.tmp"
        state: absent
```

3. Finally, test sequence is updated to execute `dependency` step twice: before `prepare` and before `converge`:

```yaml
scenario:
  converge_sequence:
    - cleanup
    - dependency
    - destroy # added here to have an ability execute `molecule converge` a few times
    - create
    - prepare
    - dependency
    - converge
  test_sequence:
    - lint
    - cleanup # removes temporary file
    - dependency # installs previous version of collection
    - destroy
    - syntax
    - create
    - prepare # installs previous postgresql version and creates temporary file
    - dependency # installs current version of collection
    - converge # does upgrade
    - idempotence
    - verify
    - cleanup
    - destroy
```

All configuration is in PoC PostgreSQL collection. 
@to-bar @mkyc but I suggest not to close this task and in addition monitor [this](https://stackoverflow.com/questions/70117898/use-different-ansible-collection-versions-in-one-molecule-scenario) and [this](https://github.com/ansible-community/molecule/discussions/3319) threads as there might be more straightforward approaches.
