### ISSUE TITLE
[PoC-Pulp] Test Pulp with Epiphany using LTS

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#2722]
Steps:
- Generate metadata for packages
- Upload files and packages(with metadata) from LTS version (using pulp_files)
- Upload images from LTS version (using pulp_container)
- Manually change the repository role to enable Pulp repositories
- Run epicli apply

**Describe the solution you'd like**
Be able to build a cluster based on Pulp repository

**Additional context**
Generate metadata, uploading files, packages, images should be done via script

---

**DoD checklist**

* [x] Reader is able to understand the results of spike
* [x] The results of the spike are presented in a table (to show simply what are compared or researched parameters) / not applicable
* [x] Each value / cell in the results table is described more deeply below
* [x] Demo of the spike (automated as much as possible)
* [ ] Design doc updated

**Comment by rafzei** [comment]
@mkyc @romsok24 I believe this could be the next step: https://github.com/epiphany-platform/epiphany/issues/2724, please ask a question in this issue if something is not clear.

**Comment by romsok24** [comment]
The 5 steps defined in this issue description were completed 
in order to proof that we're able to build an Epiphany cluster using Pulp repository.

The following setup was used to satisfy it:
 - the environment consisting of 2 Azure VMs ( pulp machine and triggering machine ) was prepared
 - pulp instance was build using [pulp in one container](https://pulpproject.org/pulp-in-one-container/) mode
 - 2 scripts were prepared that allow running these steps:
   - assuring all pulp client and python prerequisites are met
   - generating metadata
   - uploading files, packages and images
   - assuring the progress indication is present to the operator
   both scripts are ready to be used within a pipeline - ie. on that is used for testing a new Epiphany release;
   the scripts are using pulp cli semantic in order to be easily readable 

Right now, in order to allow the epicli process to be run with pulp repository and registry
I had to made the following changes to the epicli code:
<details>
  <summary> ansible/playbooks/group_vars/all.yml </summary>
  
  ```
  ---
  # Commented as for the need of #2722 Pulp PoC
  # local_repository_url: "http://{{ hostvars[groups.repository[0]].ansible_default_ipv4.address }}/epirepo"
  # repository_url: "{{ custom_repository_url | default(local_repository_url, true) }}"
  local_repository_url: "http://20.79.223.18/pulp/content/epi_repo_12"
  repository_url: "http://20.79.223.18/pulp/content/epi_repo_12"

  local_image_registry: "{{ groups.image_registry[0] }}:5000"
  image_registry_address: "{{ custom_image_registry_address | default(local_image_registry, true) }}"

  kubeconfig:
    local: "{{ inventory_dir }}/kubeconfig"
    remote: /etc/kubernetes/admin.conf

  # https://github.com/ansible/ansible/issues/57189
  yum_lock_timeout: 300

  global_architecture_alias:
    x86_64: amd64
    aarch64: arm64
  ```
</details>

<details>
  <summary>ansible/playbooks/roles/helm/defaults/main.yml</summary>

  ```
  ---
  system_chart_namespace: epi-charts
  system_chart_repo_name: system-charts
  system_chart_repo_path: /charts/system
  # Use custom repository or use ssh tunnel for Helm
  # Commented as for the need of #2722 Pulp PoC
  # system_chart_repo_url: "{{ (custom_repository_url | default('http://localhost/epirepo', true)) ~ system_chart_repo_path }}"
  system_chart_repo_url: "{{ repository_url }}"
  helm_archive_regexp:
    x86_64: "^helm-v([0-9.]+)-linux-amd64.tar.gz$"
    aarch64: "^helm-v([0-9.]+)-linux-arm64.tar.gz$"


  ```

</details>

<details>
  <summary>ansible/playbooks/roles/repository/files/client/Debian/add-epirepo-client.sh</summary>

  ```
#!/bin/bash -eu

REPOSITORY_URL=$1

# Commented as for the need of #2722 Pulp PoC
# echo "deb [trusted=yes] $REPOSITORY_URL/packages ./" > /etc/apt/sources.list.d/epirepo.list
case $1 in
    *"http"*)
        echo "deb [trusted=yes] $REPOSITORY_URL /"  > /etc/apt/sources.list.d/epirepo.list;;
    *)
        echo "deb [trusted=yes] $REPOSITORY_URL/packages ./"  > /etc/apt/sources.list.d/epirepo.list;;
esac

apt update
```
</details>

<br>

These manual changes in the future are planned to be replace either be the epicli [custom-repo feature](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/CLUSTER.md#how-to-create-an-epiphany-cluster-using-custom-system-repository-and-docker-image-registry) ( preffered option ) or by fallback repository feature ( [EPI#2274](https://github.com/epiphany-platform/epiphany/issues/2724) ).
