### ISSUE TITLE
[BUG] [PostgreSQL] [Ubuntu] PostgreSQL's configuration files located outside of the data directory are not copied by repmgr

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#2728]
**Describe the bug**
PostgreSQL's configuration files located outside of the data directory (which applies to **Ubuntu** installations) are not copied to the cloned node by `repmgr`.
According to [docs](https://repmgr.org/docs/5.2/repmgr-standby-clone.html) to copy these files, the option `--copy-external-config-files[={samepath|pgdata}]` has to be provided to the `repmgr standby clone` command.
For RHEL all data/configuration files are stored in:
```
  config_dir:
    RedHat: /var/lib/pgsql/{ ver }/data
  data_dir:
    RedHat: /var/lib/pgsql/{ ver }/data
```
but for Ubuntu it is `/etc/postgresql/{ ver }/main`
```
  config_dir:
    Debian: /etc/postgresql/{ ver }/main
  data_dir:
    Debian: /var/lib/postgresql/{ ver }/main
```

**How to reproduce**
1. Deploy any `Ubuntu` cluster with `2 PostgreSQL` nodes and `replication` enabled
2. Compare `/etc/postgresql/10/main/postgresql-epiphany.conf` files on primary and standby nodes.

**Expected behavior**
All configuration files should be copied to the standby node 

**Environment**
- Cloud provider: [all]
- OS: [Ubuntu]

**epicli version**: [1.3.0dev].

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [ ] updated
  - [x] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [x] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [x] All conversations in PR resolved
