### ISSUE TITLE
[BUG] assert_no_postgres_nodes_number_change returning exception even if not changed value "count"

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#2737]
**Describe the bug**
In specified condition ```epicli apply``` failed with exception: "Postgresql scaling is not supported yet. Please revert your 'postgresql' count to previous value." even if no configuration changes have been done.

Review assert_no_postgres_nodes_number_change function to fix bug 

**How to reproduce**
1. execute `epicli apply -f config.yml` twice

**Expected behavior**
Scripts should pass all assetions since no changes have been done

**Config files**
Problem occurs when specified configuration is used:

```yaml
specification:
  components:
        kubernetes_master:
          count: 1
        postgresql:
          count: 0
---
kind: configuration/feature-mapping
title: Feature mapping to roles
name: default
specification:
  roles_mapping:
    kubernetes_master:
    - kubernetes-master
    - helm
    - applications
    - node-exporter
    - filebeat
    - firewall
    - vault
    - postgresql
...
```

**Environment**
- Cloud provider:  All
- OS: All

**epicli version**: 1.2.0

**Additional context:**
Comparison uses values from inventory and configuration files. In this specified configuration values don't meet.

---

**DoD checklist**

* [x] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [ ] Case covered by automated test (if possible)
* [x] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Backport tasks created / doesn't need to be backported
