### ISSUE TITLE
[FEATURE REQUEST] Add configuration option to Keycloak for PROXY_ADDRESS_FORWARDING env. variable

### ISSUE THREAD

**Issue by GrzegorzKlankABB** [epiphany-platform/epiphany#2785]
**Is your feature request related to a problem? Please describe.**
I would like Keycloak service to be aware of being behind HAPRoxy and inform it to use X-Forwarded-... headers for proper JWT issuer information. At the moment I manually edit keycloak stateful set to include PROXY_ADDRESS_FORWARDING environment variable.

**Describe the solution you'd like**
I would like Epiphany yml configuration file to have flag in auth-service application config that would translate to PROXY_ADDRESS_FORWARDING true/false value passed as environment variable to the keycloak pod. The default value can be set to false to maintain backward compatibility. 

**Describe alternatives you've considered**

**Additional context**

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Schema updated / doesn't need to be updated
* [ ] Feature has automated tests
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [x] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license
* [ ] Backport tasks created / doesn't need to be backported

**Comment by plirglo** [comment]
OS does not matter during testing process since application works in k8s cluster.
Tested on Ubuntu with application setup:
```yaml
kind: configuration/applications
title: Kubernetes Applications Config
name: default
specification:
  applications:
  - name: auth-service
    enabled: true
    image_path: epiphanyplatform/keycloak:14.0.0
    use_local_image_registry: true
    service:
      proxy_address_forwarding: true
```
By default ```proxy_address_forwarding``` is set to ```false```

Configuration deployed:

![image.png](https://images.zenhubusercontent.com/5ef9f41844c19c2f7f1c83e8/e0fa6410-b40c-45b9-ab48-6c116b860931)

![image.png](https://images.zenhubusercontent.com/5ef9f41844c19c2f7f1c83e8/977425b3-d35e-40af-8ca3-9f849ad8ddab)

![image.png](https://images.zenhubusercontent.com/5ef9f41844c19c2f7f1c83e8/ffd836c8-5ae9-42f3-8b12-5a012761fffa)
