### ISSUE TITLE
[BUG][v1.0.x][RHEL/CentOS] RabbitMQ backup fails: `/usr/bin/env: python3: No such file or directory`

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#2920]
**Describe the bug**
Backup of RabbitMQ component fails on RHEL/CentOS.
```
2022-01-25T10:22:42.3740640Z[38;21m10:22:42 INFO cli.engine.ansible.AnsibleCommand - TASK [backup : Save definitions in a json file] ********************************
2022-01-25T10:22:43.2903485Z[31;21m10:22:43 ERROR cli.engine.ansible.AnsibleCommand - fatal: [ci-v10recazrhflannel-rabbitmq-vm-0]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/rabbitmqadmin export /var/lib/rabbitmq/definitions/definitions-20220125-102233.json\n", "delta": "0:00:00.006261", "end": "2022-01-25 10:22:43.186502", "msg": "non-zero return code", "rc": 127, "start": "2022-01-25 10:22:43.180241", "stderr": "/usr/bin/env: python3: No such file or directory", "stderr_lines": ["/usr/bin/env: python3: No such file or directory"], "stdout": "", "stdout_lines": []}
```

NOTE: **Please also verify the recovery playbook**

**How to reproduce**
1. execute `epicli apply` to deploy a v1.0 cluster with RabbitMQ component enabled
2. execute `epicli backup -b /build/directory -f /backup/config.yml` 

**Expected behavior**
Backup of RabbitMQ component should be successful

**Config files**
Backup config
```yaml
---
kind: configuration/backup
title: Backup Config
provider: azure
name: default
specification:
  components:
    load_balancer:
      enabled: true
    logging:
      enabled: true
    monitoring:
      enabled: true
    postgresql:
      enabled: true
    rabbitmq:
      enabled: true
    kubernetes:
      enabled: true
```

**Environment**
- Cloud provider: [all]
- OS: [Ubuntu]

**epicli version**: v1.0
---

**DoD checklist**

* [x] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [ ] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [ ] Case covered by automated test (if possible)
* [x] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Backport tasks created / doesn't need to be backported
