### ISSUE TITLE
[BUG] Restore the possibility of choosing the availability zone in AWS

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#2979]
**Describe the bug**
In #2939 we have removed the option to choose the availability zone. Now the availability zone is selected automatically by AWS. While in most cases it is not a problem, in the case of aarch64 installation (a1 instances) there may be an issue as some instances may not be supported in the requested availability zone.

```
2022-02-14T14:49:22.3181271Z[31;21m14:49:22 ERROR cli.src.terraform.TerraformCommand - Error: Error launching source instance: Unsupported: Your requested instance type (a1.large) is not supported in your requested Availability Zone (eu-central-1c). Please retry your request by not specifying an Availability Zone or choosing eu-central-1a, eu-central-1b.
2022-02-14T14:49:22.3193805Z[38;21m14:49:22 INFO cli.src.terraform.TerraformCommand - 	status code: 400, request id: fad37b7b-f38e-4cf6-adc1-5207b4fc8f72


2022-02-14T14:39:46.5399721Z[31;21m14:39:46 ERROR cli.src.terraform.TerraformCommand - Error: Error launching source instance: Unsupported: Your requested instance type (a1.large) is not supported in your requested Availability Zone (eu-west-1b). Please retry your request by not specifying an Availability Zone or choosing eu-west-1a, eu-west-1c.
2022-02-14T14:39:46.5401896Z[38;21m14:39:46 INFO cli.src.terraform.TerraformCommand - 	status code: 400, request id: 8e1f31f0-dc2c-4c54-b195-3036adedddc2

```
Available regions:
https://aws.amazon.com/about-aws/whats-new/2019/08/amazon-ec2-a1-instances-are-now-available-in-additional-regions/

**How to reproduce**
1. execute `epicli apply` and try to deploy an aarch64 cluster

**Expected behavior**
The cluster should be deployed with no issues

**Config files**

```yaml
...
  components:
    kafka:
      count: $(kafka_vms)
      machine: kafka-machine
    kubernetes_master:
      count: $(master_vms)
      machine: kubernetes-master-machine
    kubernetes_node:
      count: $(node_vms)
      machine: kubernetes-node-machine
    load_balancer:
      count: $(lb_vms)
      machine: load-balancer-machine
    logging:
      count: $(log_vms)
      machine: logging-machine
    monitoring:
      count: $(monitoring_vms)
      machine: monitoring-machine
    postgresql:
      count: $(postgresql_vms)
      machine: postgresql-machine
    rabbitmq:
      count: $(rabbitmq_vms)
      machine: rabbitmq-machine
    opendistro_for_elasticsearch:
      count: $(opendistro_vms)
      machine: logging-machine
    repository:
      count: 1
      machine: repository-machine
  name: $(cluster_name)
  prefix: '$(prefix)'
title: Epiphany cluster Config
---
kind: infrastructure/virtual-machine
name: kafka-machine
provider: aws
based_on: kafka-machine
specification:
  size: a1.xlarge
---
kind: infrastructure/virtual-machine
name: kubernetes-master-machine
provider: aws
based_on: kubernetes-master-machine
specification:
  size: a1.large
---
kind: infrastructure/virtual-machine
name: kubernetes-node-machine
provider: aws
based_on: kubernetes-node-machine
specification:
  size: a1.large
---
kind: infrastructure/virtual-machine
name: logging-machine
provider: aws
based_on: logging-machine
specification:
  size: a1.large
---
kind: infrastructure/virtual-machine
name: monitoring-machine
provider: aws
based_on: monitoring-machine
specification:
  size: a1.large
---
kind: infrastructure/virtual-machine
name: postgresql-machine
provider: aws
based_on: postgresql-machine
specification:
  size: a1.large
---
kind: infrastructure/virtual-machine
name: load-balancer-machine
provider: aws
based_on: load-balancer-machine
specification:
  size: a1.medium
---
kind: infrastructure/virtual-machine
name: rabbitmq-machine
provider: aws
based_on: rabbitmq-machine
specification:
  size: a1.medium
---
kind: infrastructure/virtual-machine
name: repository-machine
provider: aws
based_on: repository-machine
specification:
  size: a1.large
```

**Environment**
- Cloud provider: [AWS]
- OS: [CentOS]

**epicli version**: [2.0.0dev]

**Additional context**

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [x] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [x] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [x] All conversations in PR resolved
