### ISSUE TITLE
[BUG] Doubled haproxy entries in prometheus.yml after an upgrade

### ISSUE THREAD

**Issue by rafzei** [epiphany-platform/epiphany#2997]
**Describe the bug**
Prometheus is failing to start after upgrade due to duplicated haproxy target in its config

**How to reproduce**
1. execute `epicli apply on ver1.3`
2. execute `epicli upgrade on ver2.0`

**Expected behavior**
Prometheus running

**Config files**
```yaml
...
  components:
    kubernetes_master:
      count: 1
      machine: kubernetes-master-machine
      configuration: default
      subnets:
      - address_pool: 10.1.1.0/24
    kubernetes_node:
      count: 1
      machine: kubernetes-node-machine
      configuration: default
      subnets:
      - address_pool: 10.1.1.0/24
    logging:
      count: 1
      machine: logging-machine
      configuration: default
      subnets:
      - address_pool: 10.1.3.0/24
    monitoring:
      count: 1
      machine: monitoring-machine
      configuration: default
      subnets:
      - address_pool: 10.1.4.0/24
    kafka:
      count: 1
      machine: kafka-machine
      configuration: default
      subnets:
      - address_pool: 10.1.5.0/24
    postgresql:
      count: 1
      machine: postgresql-machine
      configuration: default
      subnets:
      - address_pool: 10.1.6.0/24
    load_balancer:
      count: 1
      machine: load-balancer-machine
      configuration: default
      subnets:
      - address_pool: 10.1.7.0/24
    rabbitmq:
      count: 1
      machine: rabbitmq-machine
      configuration: default
      subnets:
      - address_pool: 10.1.8.0/24
    ignite:
      count: 0
      machine: ignite-machine
      configuration: default
      subnets:
      - address_pool: 10.1.9.0/24
    opendistro_for_elasticsearch:
      count: 0
      machine: logging-machine
      configuration: default
      subnets:
      - address_pool: 10.1.10.0/24
    repository:
      count: 1
      machine: repository-machine
      configuration: default
      subnets:
      - address_pool: 10.1.11.0/24
    single_machine:
      count: 0
      machine: single-machine
      configuration: default
      subnets:
      - address_pool: 10.1.1.0/24
version: 1.3.0
```

**Environment**
Faced on Ubuntu 20.04 Azure

**epicli version**: [`epicli --version`]
1.3 -> 2.0
**Additional context**
This is most probably related to this change: https://github.com/epiphany-platform/epiphany/commit/12b99bfeb76deb977133393ddcb768b17e4e7a3d#diff-5737624263c568e51436b0b0b7ac25c161beebf7ceae84954b7339f1e5b6aaa6R168

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [ ] updated
  - [x] not needed
- Backport tasks
  - [x] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [x] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [x] All conversations in PR resolved
