### ISSUE TITLE
[BUG] `disk_size_gb` hardcoded in `/usr/local/epicli/data/azure/defaults/infrastructure/virtual-machine.yml`

### ISSUE THREAD

**Issue by wkalbar** [epiphany-platform/epiphany#3004]
**NOTE: See comment from @przemyslavic  below, should be a simple backport to add this 1.0.3**

**Describe the bug**
Variable `disk_size_gb` for VMs OS disks used in config.yml is overwritten by variable in `/usr/local/epicli/data/azure/defaults/infrastructure/virtual-machine.yml`

**How to reproduce**
1. execute `epicli init ... (with params)`
2. edit config file - change variable `disk_size_gb` to any value other than default 32GB
3. execute `epicli apply ...`

**Expected behavior**
VMs should have OS disk size equal to value of `disk_size_gb` variable. Instead of this they have still 32Gb OS disks.

**Config files**
n/a

**Environment**
- Cloud provider: Azure
- OS: Ubuntu 18.046 LTS

**epicli version**: 1.0.2

**Additional context**
There is workaround to change this variable in `/usr/local/epicli/data/azure/defaults/infrastructure/virtual-machine.yml` inside container. But it's still workaround.

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [ ] updated
  - [x] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [x] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [x] All conversations in PR resolved

**Comment by seriva** [comment]
Hey @wkalbar,

Did you define it properly inside your input config:

```yaml
...
---
kind: infrastructure/virtual-machine
title: "Virtual Machine Infra"
provider: azure
name: default
version: 1.0.2
specification:
  storage_os_disk:
    disk_size_gb: 64 #for example
---
...
```

Pls add your config yaml so we can have a look what might be going on.

**Comment by wkalbar** [comment]
`grep -B 5 disk_size_gb kilo-22061.yml`
```
  storage_os_disk:
    delete_on_termination: false
    managed: false
    caching: ReadWrite
    create_option: FromImage
    disk_size_gb: 64
--
title: Virtual Machine Infra
provider: azure
name: repository-machine
specification:
  storage_os_disk:
    disk_size_gb: 64
```

**Comment by przemyslavic** [comment]
What works for me is:
```yaml
...    
  components:
    repository:
      count: 1
    kubernetes_master:
      count: 1
    kubernetes_node:
      count: 1
    logging:
      count: 0
    monitoring:
      count: 0
    kafka:
      count: 0
    postgresql:
      count: 0
    load_balancer:
      count: 0
    rabbitmq:
      count: 0
version: 1.0.2
---
kind: infrastructure/virtual-machine
name: kubernetes-master-machine
provider: azure
based_on: kubernetes-master-machine
specification:
  storage_os_disk:
    disk_size_gb: 128
---
kind: infrastructure/virtual-machine
name: kubernetes-node-machine
provider: azure
based_on: kubernetes-node-machine
specification:
  storage_os_disk:
    disk_size_gb: 256
```

If you have a full configuration (generated from init --full) you have to attach:
```
  storage_os_disk:
    disk_size_gb: xxx
```
to the spec for each machine you want to change the disk size for.

Nevertheless, I confirm that changing the disk in only one place for the default machine is not working properly. It works fine starting form v1.1.0.

Comparing v1.0 to v1.1:
https://github.com/epiphany-platform/epiphany/blob/v1.0/core/src/epicli/cli/engine/schema/DefaultMerger.py
https://github.com/epiphany-platform/epiphany/blob/v1.1/core/src/epicli/cli/engine/schema/DefaultMerger.py
This has been added:
```
        default_config = select_first(self.docs, lambda x: x.name == 'default' and x.kind == doc.kind)

        if default_config is not None:
            merge_objdict(default_doc, default_config)

```
I think this could be the reason.
