### ISSUE TITLE
[BUG] Upgrade from v1.0.3 LTS to v1.3.1 fails installing docker dependencies on Ubuntu

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#3160]
**Describe the bug**
There is an issue installing docker dependencies on Ubuntu environments while upgrading epicli from v1.0.3 to v1.3.1.
```
09:45:29 INFO cli.engine.ansible.AnsibleCommand - TASK [docker : Install Docker packages] ****************************************
09:45:30 ERROR cli.engine.ansible.AnsibleCommand - fatal: [ci-10to13azubflannel-repository-vm-0]: FAILED! => {"cache_update_time": 1653384819, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'containerd.io=1.5.11-*' 'docker-ce-cli=5:20.10.8*' 'docker-ce-rootless-extras=5:20.10.8*' 'docker-ce=5:20.10.8*'' failed: E: Packages were downgraded and -y was used without --allow-downgrades.
", "rc": 100, "stderr": "E: Packages were downgraded and -y was used without --allow-downgrades.
", "stderr_lines": ["E: Packages were downgraded and -y was used without --allow-downgrades."], "stdout": "Reading package lists...
Building dependency tree...
Reading state information...
Suggested packages:
  aufs-tools cgroupfs-mount | cgroup-lite
Recommended packages:
  pigz docker-scan-plugin slirp4netns
The following NEW packages will be installed:
  docker-ce-rootless-extras
The following packages will be upgraded:
  docker-ce docker-ce-cli
The following packages will be DOWNGRADED:
  containerd.io
2 upgraded, 1 newly installed, 1 downgraded, 0 to remove and 0 not upgraded.
", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Suggested packages:", "  aufs-tools cgroupfs-mount | cgroup-lite", "Recommended packages:", "  pigz docker-scan-plugin slirp4netns", "The following NEW packages will be installed:", "  docker-ce-rootless-extras", "The following packages will be upgraded:", "  docker-ce docker-ce-cli", "The following packages will be DOWNGRADED:", "  containerd.io", "2 upgraded, 1 newly installed, 1 downgraded, 0 to remove and 0 not upgraded."]}
```

The problem is that in v1.0 we install `containerd` without setting a specific version, which means that the latest version is installed. During the upgrade, we try to install a specific version that is older than the one already installed, causing the task to fail. I think we should either keep the newer version or uninstall the previous one if it's newer before installing the fixed one.

v1.0
```
- name: Install Docker packages
  package:
    name: "{{ _packages[ansible_os_family] }}"
    state: present
  vars:
    _packages:
      Debian:
        - containerd.io
        - docker-ce-cli={{ docker_version.Debian }}
        - docker-ce={{ docker_version.Debian }}
      RedHat:
        - containerd.io
        - docker-ce-cli-{{ docker_version.RedHat }}
        - docker-ce-{{ docker_version.RedHat }}
  module_defaults:
    yum: { lock_timeout: "{{ yum_lock_timeout }}" }
```

v1.3
```
- name: Install Docker packages
  package:
    name: "{{ _packages[ansible_os_family] }}"
    state: present
  vars:
    _packages:
      Debian:
        - containerd.io={{ containerd_version }}-*
        - docker-ce-cli={{ docker_version.Debian }}
        - docker-ce-rootless-extras={{ docker_version.Debian }}
        - docker-ce={{ docker_version.Debian }}
      RedHat:
        - containerd.io-{{ containerd_version }}
        - docker-ce-cli-{{ docker_version.RedHat }}
        - docker-ce-rootless-extras-{{ docker_version.RedHat }}
        - docker-ce-{{ docker_version.RedHat }}
  module_defaults:
    yum: { lock_timeout: "{{ yum_lock_timeout }}" }
```

**How to reproduce**
1. execute `epicli apply` v1.0.3
3. execute `epicli upgrade` to v1.3

**Expected behavior**
The upgrade should be successful.

**Config files**
**Environment**
- Cloud provider: [all]
- OS: [Ubuntu]

**epicli version**:  v1.3

**Additional context**

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [x] apply
  - [x] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [x] All conversations in PR resolved
