### ISSUE TITLE
Fix configuration/feature-mapping enabling 

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#3189]
**Is your feature request related to a problem? Please describe.**
Even if role is set up ```enabled: false``` is installed if is listed in ```roles_mapping``` list.

```yaml
kind: configuration/feature-mapping
title: Feature mapping to roles
name: default
specification:
  available_roles:
  - name: postgresql
    enabled: true
  roles_mapping:
    single_machine:
    - repository
    - image-registry
    - kubernetes-master
    - helm
    - applications
    - rabbitmq
    - postgresql
    - firewall
```
Currently to not run role, role has to be removed from role_mapping list.

**Describe the solution you'd like**
Role should not be run if it's set up to false: ```enabled: false```

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [x] not needed
- Backport tasks
  - [x] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [ ] Feature has automated tests
- [x] Automated tests passed (QA pipelines)
  - [x] apply
  - [ ] upgrade
  - [ ] backup/restore
- [x] Idempotency tested
- [x] All conversations in PR resolved
- [ ] Solution meets requirements and is done according to design doc
- [x] Usage compliant with license

**Comment by seriva** [comment]
Sounds like something we have seen before: #2425

**Comment by seriva** [comment]
@plirglo This is actually not a bug but a feature ;) ```available_roles``` is a named list, so if you want to define it partially and merge it with the other entries from default you need to define the ```_merge``` tag:

```yaml
kind: configuration/feature-mapping
title: Feature mapping to roles
name: default
specification:
  available_roles:
  - _merge: true
  - name: postgresql
    enabled: true
  roles_mapping:
    single_machine:
    - repository
    - image-registry
    - kubernetes-master
    - helm
    - applications
    - rabbitmq
    - postgresql
    - firewall
```

Otherwise it will not merge but use the entire listing in defaults. More information here: https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/CONFIGURATION_FILE.md
