### ISSUE TITLE
[BUG] epicli apply fails when 'rook' feature is absent in 'configuration/feature-mappings' doc

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#3226]
**Describe the bug**
epicli fails with error:
```
TASK [rook : RedHat fix | Create helm's binary symlink] ************************
12:52:45 INFO cli.src.ansible.AnsibleCommand - fatal: [tobar-aw-alma-arm-kubernetes-master-vm-0]: FAILED! => {"msg": "The conditional check 'specification.enabled' failed. The error was: error while evaluating conditional (specification.enabled): 'specification' is undefined\n\nThe error appears to be in '/workspaces/epiphany/clusters/build/aw-alma-arm/ansible/roles/rook/tasks/main.yml': line 7, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  block:\n    - name: RedHat fix | Create helm's binary symlink\n      ^ here\n"}
```

**How to reproduce**
1. remove `rook` mapping for `kubernetes_master` component in `configuration/feature-mappings` doc
2. execute `epicli apply`

**Expected behavior**
rook playbook should be skipped - since there is no such group in inventory

**Config files**
```
---
kind: configuration/feature-mappings
title: Feature mapping to components
name: default
specification:
  mappings:
    kafka:
    - zookeeper
    - jmx-exporter
    - kafka
    - kafka-exporter
    - node-exporter
    - filebeat
    - firewall
    rabbitmq:
    - rabbitmq
    - node-exporter
    - filebeat
    - firewall
    logging:
    - logging
    - opensearch-dashboards
    - node-exporter
    - filebeat
    - firewall
    load_balancer:
    - haproxy
    - node-exporter
    - filebeat
    - firewall
    monitoring:
    - prometheus
    - grafana
    - node-exporter
    - filebeat
    - firewall
    postgresql:
    - postgresql
    - postgres-exporter
    - node-exporter
    - filebeat
    - firewall
    custom:
    - repository
    - image-registry
    - kubernetes-master
    - node-exporter
    - filebeat
    - rabbitmq
    - postgresql
    - prometheus
    - grafana
    - node-exporter
    - logging
    - firewall
    - rook
    single_machine:
    - repository
    - image-registry
    - kubernetes-master
    - helm
    - applications
    - rabbitmq
    - postgresql
    - firewall
    - rook
    kubernetes_master:
    - kubernetes-master
    - helm
    - applications
    - node-exporter
    - filebeat
    - firewall
    kubernetes_node:
    - kubernetes-node
    - node-exporter
    - filebeat
    - firewall
    opensearch:
    - opensearch
    - node-exporter
    - filebeat
    - firewall
    repository:
    - repository
    - image-registry
    - firewall
    - filebeat
    - node-exporter
version: 2.0.1dev
provider: aws
```

**Environment**
- Cloud provider: All
- OS: All

**epicli version**: 2.0.1dev

**Additional context**
n/a

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [x] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [x] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [x] All conversations in PR resolved
