### ISSUE TITLE
[BUG] [v1.0] CentOS 7.9.2009 AMI no longer available

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#3299]
**Describe the bug**
The AMIs we use in epicli v1.0 for CentOS deployments on AWS (`CentOS 7.9.2009 x86_64` and `CentOS 7.9.2009 aarch64`) are no longer available due to security updates. For both `x64` and `aarch64` architectures. 
The error is as follows `ERROR epicli - Expected 1 OS Image matching Name: CentOS 7.9.2009 x86_64 but received: 0`
On November 14, new images were published (`CentOS Linux 7 aarch64 - 2211` and `CentOS Linux 7 x86_64 - 2211`).
We need to change the defaults to use the latest available CentOS 7.9 images.

**How to reproduce**
1. Try to deploy any epicli v1.0.7 cluster

**Expected behavior**
The cluster should be deployed without any issues.

**Config files**

**Environment**
- Cloud provider: [AWS]
- OS: [Centos 7]

**epicli version**: [`1.0.7`]

**Additional context**
To workaround the problem, add the following documents to your data.yaml to deploy CentOS cluster on AWS:
```
kind: epiphany-cluster
title: Epiphany cluster Config
provider: aws
name: default
specification:
  cloud:
    default_os_image: centos-7-x86_64
```
```
---
kind: infrastructure/cloud-os-image-defaults
title: "Cloud OS Image Defaults"
name: default
provider: aws
specification:
  ubuntu-18.04-x86_64: ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20210323
  redhat-7-x86_64: RHEL-7.9_HVM-20210208-x86_64-0-Hourly2-GP2
  centos-7-x86_64: CentOS Linux 7 x86_64 - 2211
  centos-7-arm64: CentOS Linux 7 aarch64 - 2211
```

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [x] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [ ] Feature has automated tests
- [x] Automated tests passed (QA pipelines)
  - [x] apply
  - [x] upgrade
  - [ ] backup/restore
- [x] Idempotency tested
- [x] All conversations in PR resolved
