### ISSUE TITLE
[BUG] [v2.0] [AWS] AlmaLinux OS 8.4 AMIs no longer available

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#3302]
**Describe the bug**
The AMIs we use in epicli v2.0 for AlmaLinux deployments on AWS (`AlmaLinux OS 8.4.20211015 x86_64` and `AlmaLinux OS 8.4.20211015 aarch64`) are no longer available for both x64 and aarch64 architectures.
The error returned by epicli is as follows `ERROR epicli - Expected 1 OS Image matching Name: AlmaLinux OS 8.4.20211015 x86_64 but received: 0`.

For x64 deployments as a workaround, one can use `AlmaLinux OS 8.6.20220901 x86_64` image that seems to be working fine at the time of testing today.

For aarch64 there is an additional issue with `pgaudit15_13-1.5.0` package that is no longer available in postgresql repository.
So we need to find another source for the v1.5.0 package or adjust existing scripts to download v1.5.2.

As a temporary solution, one can remove `pgaudit` from the [requirements list](https://github.com/epiphany-platform/epiphany/blob/develop/ansible/playbooks/roles/repository/files/download-requirements/requirements/aarch64/redhat/packages.yml#L78) and **NOT** enable this extension in [postgresql configuration](https://github.com/epiphany-platform/epiphany/blob/develop/schema/common/defaults/configuration/postgresql.yml#L75).
Then the cluster should by deployed with no issues and `pgaudit` can be installed later manually.

For some time now, it has also been possible to deploy an aarch64 cluster in Azure. However, the images available there are mainly Ubuntu 18.04, 20.04, 22.04, 22.10 and a few others, there is no AlmaLinux at all as of now. In this case, to deploy an aarch64 cluster on Azure we need to adjust the download-requirements scripts anyway to support other systems, not just AlmaLinux. So additional work would also be required.

To deploy AlmaLinux 8.6 clusters on AWS add the following documents to your data.yaml:
```
kind: epiphany-cluster
title: Epiphany cluster Config
provider: aws
name: default
specification:
  cloud:
    default_os_image: almalinux-8-x86_64
```
```
---
kind: infrastructure/cloud-os-image-defaults
title: "Cloud OS Image Defaults"
name: default
provider: aws
specification:
  almalinux-8-arm64: AlmaLinux OS 8.6.20220901 aarch64
  almalinux-8-x86_64: AlmaLinux OS 8.6.20220901 x86_64
  rhel-8-x86_64: RHEL-8.4.0_HVM-20210825-x86_64-0-Hourly2-GP2
  ubuntu-20.04-x86_64: ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20221010
```

**Environment**
- Cloud provider: [AWS ]
- OS: [AlmaLinux]

**epicli version**: [2.0.2]

**Additional context**

---

**DoD checklist**

- Changelog
  - [ ] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [ ] not needed
- Schema
  - [ ] updated
  - [ ] not needed
- Backport tasks
  - [ ] created
  - [ ] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [ ] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [ ] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [ ] All conversations in PR resolved
