### ISSUE TITLE
ERROR epicli - list index out of range[BUG] Short description of the bug

### ISSUE THREAD

**Issue by rahulrajanrepo** [epiphany-platform/epiphany#3393]
Hi Team, 
I'm getting the below error while running the epiphany file in no-infra mode. Have attached the yaml file.

ERROR epicli - list index out of range

Steps:
1. docker run -it -v "/home/hitachi/serd":/shared --rm ghcr.io/hitachienergy/epicli:2.0.7
2. epicli  --debug 4 apply -f onprem207.yml --vault-password 1234567890 --no-infra
[onprem207.zip](https://github.com/hitachienergy/epiphany/files/12585234/onprem207.zip)

![image](https://github.com/hitachienergy/epiphany/assets/49981814/aef1bb14-7899-490b-97d8-9f9c2d35af6c)

**Comment by seriva** [comment]
Hey,
Pretty sure you forgot to add proper **merge** tag for the feature list so it knows how to merge properly:

```yaml
kind: configuration/features
title: Features to be enabled/disabled
name: default
specification:
  features:
  - _merge: true
  - name: repository
    enabled: true
  - name: kubernetes-master
    enabled: true
  - name: kubernetes-node
    enabled: true
  - name: logging
    enabled: true
  - name: opensearch
    enabled: true
  - name: opensearch-dashboards
    enabled: true
  - name: prometheus
    enabled: true
  - name: grafana
    enabled: true
  - name: keycloak
    enabled: false 
```

Explanation can be found here: 
https://github.com/hitachienergy/epiphany/blob/develop/docs/home/howto/CONFIGURATION_FILE.md#configuration-file

Cheers
Luuk
