### ISSUE TITLE
Elasticsearch-curator to be able to curate logs depending on % of drive used

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#734]
Current implementation of elasticsearch-curator allows to use days for deleting logs. 

```yaml
kind: configuration/elasticsearch-curator
title: "ElasticSearch curator"
name: default
specification:
  indices_retention_days: 30
  debian_curator_version: "5.5.4_amd64"
  redhat_curator_version: "5.5.4-1.x86_64"
```

Introduce functionality to allow user to specify percentage of hard disk to use for logs.
Like: 
`indices_drive_usage_percent: 60%`
