### ISSUE TITLE
Refactor cluster definition cloud node.

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#960]
Currently in the cloud node of a cluster definition we have some network specific configs for Network, Azure and AWS. However most of these are grouped directly under the cloud node making it difficult to understand what is being used for what.  In this task we want to move the specific configs under subnodes so it will be easier to understand what is used for what:

```yaml
  cloud:
    azure:
      subscription_name: YOUR-SUB-NAME
      use_service_principal: false
    aws:
      credentials:
        key: XXXX-XXXX-XXXX
        secret: XXXXXXXXXXXXXXXX      
    network:
      vnet_address_pool: 10.1.0.0/20
      use_public_ips: false
      region: eu-west-2
      use_network_security_groups: true
```
